"""
Neuromorphic Co-Development Framework - Developmental Genome Schema

This module defines the Pydantic schema for the developmental genome that
LLM agents use to propose and modify neuromorphic substrate architecture.

The genome is the executable contract between LLM agents and the SNN.
LLM agents propose changes by emitting partial genome deltas; the schema
validates them, and the compiler builds the runnable Brian2 network.

Author: Generated by Mistral Vibe
Date: 2026-09-01
"""

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional, Union
from pydantic import (
    BaseModel,
    Field,
    field_validator,
    model_validator,
    ConfigDict,
)
import numpy as np

# =============================================================================
# TYPE DEFINITIONS
# =============================================================================

class NeuronModel(str, Enum):
    """Supported neuron models for the substrate."""
    LIF = "LIF"  # Leaky Integrate-and-Fire
    ADAPTIVE_LIF = "AdaptiveLIF"  # LIF with spike-frequency adaptation
    IZHIKEVICH = "Izhi"  # Izhikevich model
    EXPONENTIAL_IF = "ExpIF"  # Exponential Integrate-and-Fire
    HH = "HodgkinHuxley"  # Hodgkin-Huxley (computationally expensive)


class SynapseType(str, Enum):
    """Types of synaptic connections."""
    STATIC = "static"  # Fixed weight
    STD = "stdp"  # Spike-timing dependent plasticity
    THREE_FACTOR = "three_factor"  # Three-factor learning (neuromodulated STDP)
    HEBBIAN = "hebbian"  # Classical Hebbian
    ANTI_HEBBIAN = "anti_hebbian"  # Anti-Hebbian
    OJA = "oja"  # Oja's rule (normalized Hebbian)


class PlasticityRuleType(str, Enum):
    """Supported plasticity rule types."""
    STDP = "STDP"  # Pair-based STDP
    TRIPLET_STDP = "TripletSTDP"  # Triplet STDP
    REWARD_MODULATED_STDP = "RewardModulatedSTDP"  # RPM-STDP
    THREE_FACTOR_STDP = "ThreeFactorSTDP"  # Spike + neuromodulator + postsynaptic
    HEBBIAN = "Hebbian"
    HOMEOSTATIC = "Homeostatic"  # Synaptic scaling
    BCI = "BCI"  # BCM rule


class NeuromodulatorType(str, Enum):
    """Supported neuromodulator types (biologically inspired)."""
    DOPAMINE = "dopamine"  # Reward, motivation
    SEROTONIN = "serotonin"  # Mood, patience
    ACETYLCHOLINE = "acetylcholine"  # Focus, attention
    NOREPINEPHRINE = "norepinephrine"  # Alertness, surprise
    GABA = "gaba"  # Inhibition (special case)
    GLUTAMATE = "glutamate"  # Excitation (special case)
    CUSTOM = "custom"  # User-defined


class ConnectivityPattern(str, Enum):
    """Patterns for connecting populations."""
    FULL = "full"  # All-to-all
    SPARSE_RANDOM = "sparse_random"  # Random sparse
    SMALL_WORLD = "small_world"  # Small-world network
    SCALE_FREE = "scale_free"  # Scale-free (preferential attachment)
    ERDOS_RENYI = "erdos_renyi"  # Erdos-Renyi random graph
    GRID = "grid"  # 2D grid topology
    TORUS = "torus"  # 2D torus
    CUSTOM = "custom"  # Custom connection function


class MemoryMechanism(str, Enum):
    """Types of memory consolidation mechanisms."""
    ATTRACTOR = "attractor"  # Attractor networks
    EPISODIC = "episodic"  # Episodic memory traces
    WORKING = "working"  # Working memory (persistent activity)
    SYNAPTIC_INTELLIGENCE = "synaptic_intelligence"  # Synaptic intelligence (SI)
    ELASTIC_WEIGHT_CONSOLIDATION = "ewc"  # Elastic Weight Consolidation


class PruningStrategy(str, Enum):
    """Strategies for synaptic pruning."""
    MAGNITUDE = "magnitude"  # Prune smallest weights
    GRADIENT = "gradient"  # Prune based on gradient flow
    ACTIVITY = "activity"  # Prune least active synapses
    AGE = "age"  # Prune oldest synapses
    TEMPORAL = "temporal"  # Temporal-based (predictive reactivation)
    RANDOM = "random"  # Random pruning
    STRUCTURAL = "structural"  # Based on network topology


class NeurogenesisStrategy(str, Enum):
    """Strategies for neurogenesis (adding new neurons)."""
    RANDOM = "random"  # Random insertion
    TARGETED = "targeted"  # Add to specific populations
    ACTIVITY_DEPENDENT = "activity_dependent"  # Based on population activity
    ERROR_DRIVEN = "error_driven"  # Based on prediction error
    NOVELTY_DRIVEN = "novelty_driven"  # Based on novelty detection


class HomeostaticMechanism(str, Enum):
    """Types of homeostatic mechanisms."""
    SYNAPTIC_SCALING = "synaptic_scaling"  # Scale all synaptic weights
    INTRINSIC_PLASTICITY = "intrinsic_plasticity"  # Adjust neuronal excitability
    FIRE_RATE_HOMEOSTASIS = "fire_rate_homeostasis"  # Target firing rate
    WEIGHT_NORMALIZATION = "weight_normalization"  # Normalize synaptic weights
    SPARSENESS_REGULARIZATION = "sparseness_regularization"  # Encourage sparse activity


class TemporalPattern(str, Enum):
    """Types of temporal patterns for predictive retention."""
    CYCLIC = "cyclic"  # Regular cycles (e.g., quarterly finance)
    SEASONAL = "seasonal"  # Seasonal patterns
    EVENT_TRIGGERED = "event_triggered"  # Triggered by specific events
    USAGE_BASED = "usage_based"  # Based on usage frequency
    PREDICTIVE = "predictive"  # ML-based prediction


# =============================================================================
# CORE SCHEMA MODELS
# =============================================================================

class NeuronTypeSpec(BaseModel):
    """
    Specification for a neuron type.
    
    Defines the mathematical model and parameters for a class of neurons.
    Multiple populations can use the same neuron type.
    """
    name: str = Field(..., description="Unique identifier for this neuron type")
    model: NeuronModel = Field(
        default=NeuronModel.LIF,
        description="The neuron model to use"
    )
    
    # Common LIF parameters
    tau_m: float = Field(
        default=10.0,
        ge=0.1,
        description="Membrane time constant (ms)"
    )
    tau_ref: float = Field(
        default=2.0,
        ge=0.0,
        description="Refractory period (ms)"
    )
    v_thresh: float = Field(
        default=-50.0,
        description="Spike threshold potential (mV)"
    )
    v_reset: float = Field(
        default=-70.0,
        description="Reset potential after spike (mV)"
    )
    v_rest: float = Field(
        default=-70.0,
        description="Resting potential (mV)"
    )
    e_rev: float = Field(
        default=0.0,
        description="Reversal potential (mV)"
    )
    r: float = Field(
        default=1.0,
        ge=0.0,
        description="Membrane resistance (MΩ)"
    )
    c: float = Field(
        default=250.0,
        ge=0.0,
        description="Membrane capacitance (pF)"
    )
    
    # Adaptive LIF parameters
    tau_adapt: Optional[float] = Field(
        default=None,
        ge=0.0,
        description="Adaptation time constant (ms) - AdaptiveLIF only"
    )
    increment: Optional[float] = Field(
        default=None,
        ge=0.0,
        description="Adaptation increment per spike (mV) - AdaptiveLIF only"
    )
    
    # Slow NMDA-like current (working-memory maintenance)
    tau_slow: Optional[float] = Field(
        default=None,
        ge=0.0,
        description="Time constant (ms) of a slow recurrent current that lets "
                    "the neuron sustain activity across a delay period. When "
                    "set, the neuron gains a 'g_nmda' state variable that "
                    "recurrent 'slow_channel' synapses charge."
    )
    
    # Izhikevich parameters
    a: Optional[float] = Field(
        default=None,
        description="Izhikevich a parameter"
    )
    b: Optional[float] = Field(
        default=None,
        description="Izhikevich b parameter"
    )
    c: Optional[float] = Field(
        default=None,
        description="Izhikevich c parameter (reset voltage)"
    )
    d: Optional[float] = Field(
        default=None,
        description="Izhikevich d parameter (reset recovery)"
    )
    
    # Metadata
    description: str = Field(
        default="",
        description="Human-readable description"
    )
    
    # Note: Validation of neuron model parameters is deferred to model-level validation
    # due to Pydantic v2 field_validator behavior with enums


class SynapseTypeSpec(BaseModel):
    """
    Specification for a synapse type.
    
    Defines the synaptic dynamics and initial parameters.
    """
    name: str = Field(..., description="Unique identifier for this synapse type")
    synapse_type: SynapseType = Field(
        default=SynapseType.STATIC,
        description="The type of synaptic plasticity"
    )
    
    # Synaptic parameters
    weight: float = Field(
        default=0.5,
        description="Initial synaptic weight"
    )
    delay: float = Field(
        default=1.0,
        ge=0.0,
        description="Synaptic transmission delay (ms)"
    )
    
    # STDP parameters
    tau_plus: Optional[float] = Field(
        default=None,
        ge=0.0,
        description="Time constant for positive weight change (ms) - STDP"
    )
    tau_minus: Optional[float] = Field(
        default=None,
        ge=0.0,
        description="Time constant for negative weight change (ms) - STDP"
    )
    a_plus: Optional[float] = Field(
        default=None,
        ge=0.0,
        description="Learning rate for pre-before-post (LTP) - STDP"
    )
    a_minus: Optional[float] = Field(
        default=None,
        ge=0.0,
        description="Learning rate for post-before-pre (LTD) - STDP"
    )
    w_min: Optional[float] = Field(
        default=None,
        ge=0.0,
        description="Minimum synaptic weight - STDP"
    )
    w_max: Optional[float] = Field(
        default=None,
        ge=0.0,
        description="Maximum synaptic weight - STDP"
    )
    
    # Neuromodulated STDP / Three-factor learning
    neuromodulator: Optional[str] = Field(
        default=None,
        description="Neuromodulator that gates this synapse's plasticity"
    )
    neuromodulation_strength: Optional[float] = Field(
        default=None,
        ge=0.0,
        description="Strength of neuromodulation effect"
    )
    
    # Decay parameters
    tau_decay: Optional[float] = Field(
        default=None,
        ge=0.0,
        description="Synaptic decay time constant (ms)"
    )
    
    # Working-memory routing
    slow_channel: bool = Field(
        default=False,
        description="If True, inject into the target neuron's slow (NMDA-like) "
                    "current ('g_nmda') rather than its membrane potential. "
                    "Used for recurrent synapses that must sustain activity "
                    "across a delay period."
    )
    
    # Metadata
    description: str = Field(
        default="",
        description="Human-readable description"
    )
    
    # Note: Validation of STDP parameters is deferred to model-level validation
    # due to Pydantic v2 field_validator behavior with enums


class PopulationSpec(BaseModel):
    """
    Specification for a neuron population.
    
    A population is a group of neurons with the same type and role.
    """
    name: str = Field(..., description="Unique identifier for this population")
    neuron_type: str = Field(..., description="Name of the neuron type to use")
    size: int = Field(..., ge=1, description="Number of neurons in this population")
    
    # Position in space (for spatial connectivity)
    geometry: Optional[str] = Field(
        default=None,
        description="Spatial arrangement: 'grid', 'line', 'circle', or None"
    )
    
    # Role classification (for LLM reasoning)
    role: str = Field(
        default="general",
        description="Functional role: 'sensory', 'associative', 'motor', 'memory', etc."
    )
    
    # Initial state
    initial_v: Optional[float] = Field(
        default=None,
        description="Initial membrane potential (mV)"
    )
    
    # Noise parameters
    noise_std: float = Field(
        default=0.0,
        ge=0.0,
        description="Standard deviation of membrane potential noise (mV)"
    )
    
    # Metadata
    description: str = Field(
        default="",
        description="Human-readable description"
    )


class ConnectivityRule(BaseModel):
    """
    Rule for connecting two populations.
    
    Defines how neurons in the source population connect to neurons
    in the target population.
    """
    name: str = Field(..., description="Unique identifier for this rule")
    source: str = Field(..., description="Source population name")
    target: str = Field(..., description="Target population name")
    
    pattern: ConnectivityPattern = Field(
        default=ConnectivityPattern.SPARSE_RANDOM,
        description="Connection pattern"
    )
    
    # Connection probability / parameters
    probability: Optional[float] = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description="Connection probability (for random patterns)"
    )
    
    # For small-world
    k: Optional[int] = Field(
        default=None,
        ge=1,
        description="Number of neighbors (small-world)"
    )
    beta: Optional[float] = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description="Rewiring probability (small-world)"
    )
    
    # For scale-free
    m: Optional[int] = Field(
        default=None,
        ge=1,
        description="Number of edges per new node (scale-free)"
    )
    
    # Synapse type to use
    synapse_type: str = Field(
        ..., 
        description="Name of the synapse type to use for these connections"
    )
    
    # Weight range for initialization
    weight_mean: Optional[float] = Field(
        default=None,
        description="Mean initial weight"
    )
    weight_std: Optional[float] = Field(
        default=None,
        ge=0.0,
        description="Standard deviation of initial weight"
    )
    
    # Delay range
    delay_mean: Optional[float] = Field(
        default=None,
        ge=0.0,
        description="Mean synaptic delay (ms)"
    )
    delay_std: Optional[float] = Field(
        default=None,
        ge=0.0,
        description="Standard deviation of delay (ms)"
    )
    
    # Whether connections are bidirectional
    bidirectional: bool = Field(
        default=False,
        description="If True, create connections in both directions"
    )
    
    # Autapse (self-connections) allowed?
    allow_autapse: bool = Field(
        default=False,
        description="Allow self-connections"
    )
    
    # Metadata
    description: str = Field(
        default="",
        description="Human-readable description"
    )
    
    @model_validator(mode='after')
    def validate_pattern_params(self):
        """Validate pattern-specific parameters."""
        if self.pattern == ConnectivityPattern.SPARSE_RANDOM:
            if self.probability is None:
                raise ValueError("SPARSE_RANDOM requires probability parameter")
        elif self.pattern == ConnectivityPattern.SMALL_WORLD:
            if self.k is None or self.beta is None:
                raise ValueError("SMALL_WORLD requires k and beta parameters")
        elif self.pattern == ConnectivityPattern.SCALE_FREE:
            if self.m is None:
                raise ValueError("SCALE_FREE requires m parameter")
        return self


class PlasticityRule(BaseModel):
    """
    Plasticity rule specification.
    
    Defines how synaptic weights change based on activity.
    """
    name: str = Field(..., description="Unique identifier for this rule")
    rule_type: PlasticityRuleType = Field(..., description="Type of plasticity rule")
    
    # Applies to which synapse types
    applies_to: List[str] = Field(
        default_factory=list,
        description="List of synapse type names this rule applies to"
    )
    
    # STDP-specific parameters
    tau_plus: Optional[float] = Field(
        default=None,
        ge=0.0,
        description="Time constant for LTP (ms)"
    )
    tau_minus: Optional[float] = Field(
        default=None,
        ge=0.0,
        description="Time constant for LTD (ms)"
    )
    a_plus: Optional[float] = Field(
        default=None,
        ge=0.0,
        description="LTP learning rate"
    )
    a_minus: Optional[float] = Field(
        default=None,
        ge=0.0,
        description="LTD learning rate"
    )
    
    # Weight bounds
    w_min: Optional[float] = Field(
        default=None,
        description="Minimum weight"
    )
    w_max: Optional[float] = Field(
        default=None,
        description="Maximum weight"
    )
    
    # Neuromodulation
    neuromodulator: Optional[str] = Field(
        default=None,
        description="Neuromodulator that gates this rule"
    )
    neuromodulation_function: Optional[str] = Field(
        default=None,
        description="How neuromodulator affects plasticity: 'gate', 'scale', 'offset'"
    )
    
    # Homeostatic parameters
    target_rate: Optional[float] = Field(
        default=None,
        ge=0.0,
        description="Target firing rate for homeostatic rules (Hz)"
    )
    scaling_factor: Optional[float] = Field(
        default=None,
        ge=0.0,
        description="Scaling factor for synaptic scaling"
    )
    
    # When to apply (pre/post synaptic?)
    pre_synaptic: bool = Field(
        default=True,
        description="Apply rule based on pre-synaptic activity"
    )
    post_synaptic: bool = Field(
        default=True,
        description="Apply rule based on post-synaptic activity"
    )
    
    # Metadata
    description: str = Field(
        default="",
        description="Human-readable description"
    )


class NeuromodulatorSpec(BaseModel):
    """
    Specification for a neuromodulator.
    
    Neuromodulators provide global signals that can gate or modulate
    plasticity and neuronal dynamics.
    """
    name: str = Field(..., description="Unique identifier for this neuromodulator")
    neuromodulator_type: NeuromodulatorType = Field(
        default=NeuromodulatorType.CUSTOM,
        description="Type of neuromodulator"
    )
    
    # Source population (where it's released from)
    source_population: Optional[str] = Field(
        default=None,
        description="Population that releases this neuromodulator"
    )
    
    # Baseline level
    baseline: float = Field(
        default=0.0,
        description="Baseline level of neuromodulator"
    )
    
    # Release parameters
    release_amount: float = Field(
        default=1.0,
        ge=0.0,
        description="Amount released per triggering event"
    )
    tau_release: float = Field(
        default=10.0,
        ge=0.0,
        description="Time constant for neuromodulator release (ms)"
    )
    tau_decay: float = Field(
        default=100.0,
        ge=0.0,
        description="Time constant for neuromodulator decay (ms)"
    )
    
    # Trigger conditions
    trigger_on_reward: bool = Field(
        default=False,
        description="Release on positive reward signals"
    )
    trigger_on_error: bool = Field(
        default=False,
        description="Release on error/punishment signals"
    )
    trigger_on_novelty: bool = Field(
        default=False,
        description="Release on novelty detection"
    )
    
    # Targets (what it affects)
    affects_populations: List[str] = Field(
        default_factory=list,
        description="Populations affected by this neuromodulator"
    )
    affects_synapses: List[str] = Field(
        default_factory=list,
        description="Synapse types affected by this neuromodulator"
    )
    affects_plasticity: List[str] = Field(
        default_factory=list,
        description="Plasticity rules affected by this neuromodulator"
    )
    
    # Effect parameters
    effect_on_excitability: Optional[float] = Field(
        default=None,
        description="Modulation of neuronal excitability"
    )
    effect_on_plasticity: Optional[float] = Field(
        default=None,
        description="Modulation of plasticity rates"
    )
    
    # Metadata
    description: str = Field(
        default="",
        description="Human-readable description"
    )


class NeurogenesisRule(BaseModel):
    """
    Rule for neurogenesis (adding new neurons).
    """
    name: str = Field(..., description="Unique identifier for this rule")
    strategy: NeurogenesisStrategy = Field(
        default=NeurogenesisStrategy.RANDOM,
        description="Strategy for adding new neurons"
    )
    
    # Target population
    target_population: str = Field(
        ..., 
        description="Population to add neurons to"
    )
    
    # How many to add
    count: int = Field(
        default=1,
        ge=1,
        description="Number of neurons to add per trigger"
    )
    count_max: Optional[int] = Field(
        default=None,
        ge=1,
        description="Maximum population size"
    )
    
    # When to trigger
    trigger_interval: Optional[float] = Field(
        default=None,
        ge=0.0,
        description="Time interval between additions (ms)"
    )
    trigger_on_activity: Optional[float] = Field(
        default=None,
        ge=0.0,
        description="Trigger when population activity exceeds this threshold (Hz)"
    )
    trigger_on_error: Optional[float] = Field(
        default=None,
        ge=0.0,
        description="Trigger when error exceeds this threshold"
    )
    trigger_on_novelty: bool = Field(
        default=False,
        description="Trigger on novelty detection"
    )
    
    # What neuron type to add
    neuron_type: str = Field(
        ..., 
        description="Neuron type for new neurons"
    )
    
    # Initial connection pattern
    initial_connectivity: Optional[str] = Field(
        default=None,
        description="Name of connectivity rule to use for new neuron connections"
    )
    
    # Metadata
    description: str = Field(
        default="",
        description="Human-readable description"
    )


class PruningRule(BaseModel):
    """
    Rule for synaptic pruning.
    
    Supports predictive retention (Phase 1.5) through temporal pattern detection.
    """
    name: str = Field(..., description="Unique identifier for this rule")
    strategy: PruningStrategy = Field(
        default=PruningStrategy.MAGNITUDE,
        description="Pruning strategy"
    )
    
    # Applies to which synapse types
    applies_to: List[str] = Field(
        default_factory=list,
        description="Synapse types this rule applies to"
    )
    
    # Pruning parameters
    threshold: Optional[float] = Field(
        default=None,
        ge=0.0,
        description="Pruning threshold (depends on strategy)"
    )
    fraction: Optional[float] = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description="Fraction of synapses to prune"
    )
    
    # Temporal parameters (for predictive retention)
    days_dormant: Optional[float] = Field(
        default=None,
        ge=0.0,
        description="Minimum days of inactivity before considering pruning"
    )
    reactivation_probability: Optional[float] = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description="Minimum predicted reactivation probability to avoid pruning"
    )
    
    # Temporal pattern matching
    temporal_pattern: Optional[TemporalPattern] = Field(
        default=None,
        description="Type of temporal pattern to detect"
    )
    pattern_period: Optional[float] = Field(
        default=None,
        ge=0.0,
        description="Period of temporal pattern (days)"
    )
    pattern_confidence: Optional[float] = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description="Minimum confidence in pattern detection"
    )
    
    # Tiered storage parameters
    demote_to_latent: bool = Field(
        default=False,
        description="Demote to latent tier instead of pruning"
    )
    archive_instead: bool = Field(
        default=False,
        description="Archive instead of pruning (compressed storage)"
    )
    
    # What to preserve
    preserve_topology: bool = Field(
        default=False,
        description="Preserve network topology information even if pruned"
    )
    preserve_metadata: bool = Field(
        default=True,
        description="Preserve metadata for potential reactivation"
    )
    
    # Reactivation triggers
    reactivation_triggers: List[str] = Field(
        default_factory=list,
        description="List of trigger conditions for reactivation (e.g., 'mention:finance', 'date:Q1')"
    )
    
    # Metadata
    description: str = Field(
        default="",
        description="Human-readable description"
    )
    
    # LLM-proposed hypothesis (for tracking)
    hypothesis: Optional[str] = Field(
        default=None,
        description="LLM scientist's hypothesis about this pruning rule"
    )
    hypothesis_date: Optional[str] = Field(
        default=None,
        description="Date hypothesis was proposed"
    )


class HomeostaticRule(BaseModel):
    """
    Homeostatic plasticity rule.
    """
    name: str = Field(..., description="Unique identifier for this rule")
    mechanism: HomeostaticMechanism = Field(
        ..., 
        description="Type of homeostatic mechanism"
    )
    
    # Applies to which populations
    applies_to: List[str] = Field(
        default_factory=list,
        description="Populations this rule applies to"
    )
    
    # Target parameters
    target_rate: Optional[float] = Field(
        default=None,
        ge=0.0,
        description="Target firing rate (Hz)"
    )
    
    # Mechanism-specific parameters
    scaling_factor: Optional[float] = Field(
        default=None,
        description="Scaling factor for synaptic scaling"
    )
    time_constant: Optional[float] = Field(
        default=None,
        ge=0.0,
        description="Time constant for homeostatic adjustment (ms)"
    )
    
    # When to apply
    apply_interval: Optional[float] = Field(
        default=None,
        ge=0.0,
        description="Interval between applications (ms)"
    )
    
    # Metadata
    description: str = Field(
        default="",
        description="Human-readable description"
    )


class MemoryConsolidationSpec(BaseModel):
    """
    Memory consolidation specification.
    
    Defines how short-term memories are consolidated into long-term memories.
    """
    mechanism: MemoryMechanism = Field(
        default=MemoryMechanism.ATTRACTOR,
        description="Primary memory mechanism"
    )
    
    # Attractor parameters
    attractor_strength: float = Field(
        default=1.0,
        ge=0.0,
        description="Strength of attractor dynamics"
    )
    attractor_radius: float = Field(
        default=0.5,
        ge=0.0,
        le=1.0,
        description="Radius of attractor basins"
    )
    
    # Consolidation schedule
    consolidation_interval: float = Field(
        default=60000.0,
        ge=0.0,
        description="Interval between consolidation cycles (ms)"
    )
    consolidation_strength: float = Field(
        default=0.1,
        ge=0.0,
        le=1.0,
        description="Strength of consolidation"
    )
    
    # Episodic memory parameters
    episode_duration: float = Field(
        default=10000.0,
        ge=0.0,
        description="Duration of an episode (ms)"
    )
    memory_retention: float = Field(
        default=0.95,
        ge=0.0,
        le=1.0,
        description="Retention rate for episodic memories"
    )
    
    # Working memory parameters
    working_memory_capacity: int = Field(
        default=100,
        ge=1,
        description="Number of items in working memory"
    )
    working_memory_timeout: float = Field(
        default=5000.0,
        ge=0.0,
        description="Timeout for working memory items (ms)"
    )
    
    # Metadata
    description: str = Field(
        default="",
        description="Human-readable description"
    )


class AttentionGatingSpec(BaseModel):
    """
    Attention/gating mechanism specification.
    
    Defines how information flow is gated through the network.
    """
    mechanism: str = Field(
        default="sigmoid",
        description="Gating mechanism: 'sigmoid', 'softmax', 'threshold', 'learnable'"
    )
    
    # Gating parameters
    threshold: Optional[float] = Field(
        default=None,
        description="Threshold for threshold gating"
    )
    temperature: Optional[float] = Field(
        default=None,
        ge=0.0,
        description="Temperature for softmax gating"
    )
    
    # Learnable gating
    learnable: bool = Field(
        default=False,
        description="Whether gating parameters are learnable"
    )
    learning_rate: Optional[float] = Field(
        default=None,
        ge=0.0,
        description="Learning rate for learnable gating"
    )
    
    # What to gate
    gates_populations: List[str] = Field(
        default_factory=list,
        description="Populations with gating"
    )
    gates_connections: List[str] = Field(
        default_factory=list,
        description="Connection rules with gating"
    )
    
    # Metadata
    description: str = Field(
        default="",
        description="Human-readable description"
    )


class TemporalDynamicsSpec(BaseModel):
    """
    Temporal dynamics specification (Phase 1.5 addition).
    
    Defines how the network handles temporal patterns and predictive retention.
    """
    # Predictive retention
    predictive_retention_enabled: bool = Field(
        default=True,
        description="Enable predictive retention for dormant topics"
    )
    
    # Reactivation prediction model
    prediction_model: str = Field(
        default="usage_based",
        description="Model for predicting reactivation: 'usage_based', 'cyclic', 'ml_classifier'"
    )
    
    # Historical tracking
    track_access_history: bool = Field(
        default=True,
        description="Track when topics/agents are accessed"
    )
    history_window_days: int = Field(
        default=730,
        ge=1,
        description="History window for pattern detection (days)"
    )
    
    # Cycle detection
    min_cycle_period_days: float = Field(
        default=7.0,
        ge=1.0,
        description="Minimum cycle period to detect (days)"
    )
    max_cycle_period_days: float = Field(
        default=365.0,
        ge=1.0,
        description="Maximum cycle period to detect (days)"
    )
    cycle_confidence_threshold: float = Field(
        default=0.7,
        ge=0.0,
        le=1.0,
        description="Confidence threshold for cycle detection"
    )
    
    # Tier parameters
    active_threshold_days: float = Field(
        default=7.0,
        ge=0.0,
        description="Days since last access to remain in 'active' tier"
    )
    latent_threshold_days: float = Field(
        default=180.0,
        ge=0.0,
        description="Days since last access before demoting to 'latent'"
    )
    archive_threshold_days: float = Field(
        default=365.0,
        ge=0.0,
        description="Days since last access before archiving"
    )
    prune_threshold_days: float = Field(
        default=730.0,
        ge=0.0,
        description="Days since last access before pruning"
    )
    
    # Reactivation probability thresholds
    min_reactivation_prob: float = Field(
        default=0.3,
        ge=0.0,
        le=1.0,
        description="Minimum reactivation probability to avoid pruning"
    )
    
    # Pre-warming
    prewarm_enabled: bool = Field(
        default=True,
        description="Enable pre-warming of latent topics"
    )
    prewarm_lead_time_hours: float = Field(
        default=24.0,
        ge=0.0,
        description="Hours before predicted reactivation to pre-warm"
    )
    
    # Metadata
    description: str = Field(
        default="",
        description="Human-readable description"
    )


class ObservableSpec(BaseModel):
    """
    Specification for network observables.
    
    Defines what high-level information the LLM agents can observe.
    """
    name: str = Field(..., description="Unique identifier for this observable")
    
    # What to observe
    observable_type: str = Field(
        ..., 
        description="Type: 'firing_rate', 'synchrony', 'latent_representation', 'attractor_stability', 'prediction_error', 'novelty', 'reward', 'memory_retrieval', 'energy', 'topology', 'plasticity_statistics', 'behavioral_performance'"
    )
    
    # Source
    source_population: Optional[str] = Field(
        default=None,
        description="Population to observe (if applicable)"
    )
    source_connection: Optional[str] = Field(
        default=None,
        description="Connection to observe (if applicable)"
    )
    
    # Aggregation
    aggregation: str = Field(
        default="mean",
        description="Aggregation method: 'mean', 'sum', 'max', 'min', 'std', 'raw'"
    )
    
    # Time window
    window_size: float = Field(
        default=100.0,
        ge=0.0,
        description="Time window for observation (ms)"
    )
    
    # Sampling
    sample_rate: float = Field(
        default=10.0,
        ge=0.0,
        description="Sampling rate (Hz)"
    )
    
    # Metadata
    description: str = Field(
        default="",
        description="Human-readable description"
    )


# =============================================================================
# THE DEVELOPMENTAL GENOME (MAIN SCHEMA)
# =============================================================================

class DevelopmentalGenome(BaseModel):
    """
    The complete developmental genome for the neuromorphic substrate.
    
    This is the primary schema that LLM agents interact with. They propose
    changes by emitting partial genome deltas, which are validated against
    this schema.
    
    The genome is hardware-agnostic — the compiler translates it to Brian2,
    Lava, or neuromorphic hardware.
    """
    model_config = ConfigDict(extra='forbid')
    
    # Version metadata
    version: str = Field(
        default="1.0",
        description="Genome schema version"
    )
    genome_id: str = Field(
        default_factory=lambda: f"genome_{np.random.randint(1000000)}",
        description="Unique identifier for this genome instance"
    )
    name: str = Field(
        default="default",
        description="Human-readable name"
    )
    description: str = Field(
        default="",
        description="Human-readable description"
    )
    created_at: str = Field(
        default_factory=lambda: "2026-09-01T00:00:00Z",
        description="Creation timestamp (ISO 8601)"
    )
    modified_at: str = Field(
        default_factory=lambda: "2026-09-01T00:00:00Z",
        description="Last modification timestamp (ISO 8601)"
    )
    
    # Core components
    neuron_types: List[NeuronTypeSpec] = Field(
        default_factory=list,
        description="Available neuron types"
    )
    synapse_types: List[SynapseTypeSpec] = Field(
        default_factory=list,
        description="Available synapse types"
    )
    populations: List[PopulationSpec] = Field(
        default_factory=list,
        description="Neuron populations"
    )
    connectivity_rules: List[ConnectivityRule] = Field(
        default_factory=list,
        description="Rules for connecting populations"
    )
    
    # Plasticity and learning
    plasticity_rules: List[PlasticityRule] = Field(
        default_factory=list,
        description="Plasticity rules"
    )
    neuromodulators: List[NeuromodulatorSpec] = Field(
        default_factory=list,
        description="Neuromodulator specifications"
    )
    
    # Structural changes
    neurogenesis_rules: List[NeurogenesisRule] = Field(
        default_factory=list,
        description="Neurogenesis rules"
    )
    pruning_rules: List[PruningRule] = Field(
        default_factory=list,
        description="Pruning rules (includes predictive retention)"
    )
    homeostatic_rules: List[HomeostaticRule] = Field(
        default_factory=list,
        description="Homeostatic rules"
    )
    
    # Memory
    memory_consolidation: MemoryConsolidationSpec = Field(
        default_factory=MemoryConsolidationSpec,
        description="Memory consolidation specification"
    )
    
    # Attention and gating
    attention_gating: AttentionGatingSpec = Field(
        default_factory=AttentionGatingSpec,
        description="Attention/gating specification"
    )
    
    # Temporal dynamics (Phase 1.5)
    temporal_dynamics: TemporalDynamicsSpec = Field(
        default_factory=TemporalDynamicsSpec,
        description="Temporal dynamics and predictive retention"
    )
    
    # Observables (what LLM can see)
    observables: List[ObservableSpec] = Field(
        default_factory=list,
        description="Network observables for LLM inspection"
    )
    
    # Metadata for tracking
    parent_genome: Optional[str] = Field(
        default=None,
        description="ID of parent genome (for evolutionary tracking)"
    )
    fitness_score: Optional[float] = Field(
        default=None,
        description="Fitness score from evaluation"
    )
    evaluation_metrics: Dict[str, float] = Field(
        default_factory=dict,
        description="Detailed evaluation metrics"
    )
    
    # LLM interaction metadata
    proposed_by: Optional[str] = Field(
        default=None,
        description="Name of LLM agent that proposed this genome"
    )
    hypothesis: Optional[str] = Field(
        default=None,
        description="Hypothesis behind this genome variant"
    )
    
    @model_validator(mode='after')
    def validate_references(self):
        """
        Validate that all references between components are valid.
        
        This ensures that:
        - Population neuron_types exist
        - ConnectivityRule source/target populations exist
        - ConnectivityRule synapse_types exist
        - PlasticityRule applies_to synapse_types exist
        - Neuromodulator affects_* references exist
        """
        # Collect all names
        neuron_type_names = {nt.name for nt in self.neuron_types}
        synapse_type_names = {st.name for st in self.synapse_types}
        population_names = {p.name for p in self.populations}
        plasticity_rule_names = {pr.name for pr in self.plasticity_rules}
        neuromodulator_names = {nm.name for nm in self.neuromodulators}
        connectivity_rule_names = {cr.name for cr in self.connectivity_rules}
        
        # Validate populations
        for pop in self.populations:
            if pop.neuron_type not in neuron_type_names:
                raise ValueError(
                    f"Population '{pop.name}' references unknown neuron type '{pop.neuron_type}'"
                )
        
        # Validate connectivity rules
        for cr in self.connectivity_rules:
            if cr.source not in population_names:
                raise ValueError(
                    f"Connectivity rule '{cr.name}' references unknown source population '{cr.source}'"
                )
            if cr.target not in population_names:
                raise ValueError(
                    f"Connectivity rule '{cr.name}' references unknown target population '{cr.target}'"
                )
            if cr.synapse_type not in synapse_type_names:
                raise ValueError(
                    f"Connectivity rule '{cr.name}' references unknown synapse type '{cr.synapse_type}'"
                )
        
        # Validate plasticity rules
        for pr in self.plasticity_rules:
            for applies_to in pr.applies_to:
                if applies_to not in synapse_type_names:
                    raise ValueError(
                        f"Plasticity rule '{pr.name}' references unknown synapse type '{applies_to}'"
                    )
        
        # Validate neuromodulators
        for nm in self.neuromodulators:
            if nm.source_population and nm.source_population not in population_names:
                raise ValueError(
                    f"Neuromodulator '{nm.name}' references unknown source population '{nm.source_population}'"
                )
            for pop in nm.affects_populations:
                if pop not in population_names:
                    raise ValueError(
                        f"Neuromodulator '{nm.name}' references unknown population '{pop}'"
                    )
            for syn in nm.affects_synapses:
                if syn not in synapse_type_names:
                    raise ValueError(
                        f"Neuromodulator '{nm.name}' references unknown synapse type '{syn}'"
                    )
            for pr_name in nm.affects_plasticity:
                if pr_name not in plasticity_rule_names:
                    raise ValueError(
                        f"Neuromodulator '{nm.name}' references unknown plasticity rule '{pr_name}'"
                    )
        
        # Validate neurogenesis rules
        for ng in self.neurogenesis_rules:
            if ng.target_population not in population_names:
                raise ValueError(
                    f"Neurogenesis rule '{ng.name}' references unknown population '{ng.target_population}'"
                )
            if ng.neuron_type not in neuron_type_names:
                raise ValueError(
                    f"Neurogenesis rule '{ng.name}' references unknown neuron type '{ng.neuron_type}'"
                )
            if ng.initial_connectivity and ng.initial_connectivity not in connectivity_rule_names:
                raise ValueError(
                    f"Neurogenesis rule '{ng.name}' references unknown connectivity rule '{ng.initial_connectivity}'"
                )
        
        return self
    
    def get_population(self, name: str) -> Optional[PopulationSpec]:
        """Get a population by name."""
        for pop in self.populations:
            if pop.name == name:
                return pop
        return None
    
    def get_neuron_type(self, name: str) -> Optional[NeuronTypeSpec]:
        """Get a neuron type by name."""
        for nt in self.neuron_types:
            if nt.name == name:
                return nt
        return None
    
    def get_synapse_type(self, name: str) -> Optional[SynapseTypeSpec]:
        """Get a synapse type by name."""
        for st in self.synapse_types:
            if st.name == name:
                return st
        return None
    
    def get_connectivity_rule(self, name: str) -> Optional[ConnectivityRule]:
        """Get a connectivity rule by name."""
        for cr in self.connectivity_rules:
            if cr.name == name:
                return cr
        return None
    
    def to_dict(self) -> Dict[str, Any]:
        """Serialize to dictionary (for JSON storage)."""
        return self.model_dump(mode='json')
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'DevelopmentalGenome':
        """Deserialize from dictionary."""
        return cls.model_validate(data)
    
    def save(self, path: str) -> None:
        """Save genome to JSON file."""
        import json
        with open(path, 'w') as f:
            json.dump(self.to_dict(), f, indent=2)
    
    @classmethod
    def load(cls, path: str) -> 'DevelopmentalGenome':
        """Load genome from JSON file."""
        import json
        with open(path, 'r') as f:
            data = json.load(f)
        return cls.from_dict(data)


# =============================================================================
# GENOME DELTA (for LLM proposals)
# =============================================================================

class GenomeDelta(BaseModel):
    """
    A delta/proposal for modifying a genome.
    
    LLM agents emit these to propose changes. The delta is applied
    to a genome to create a new variant.
    """
    # Metadata
    delta_id: str = Field(
        default_factory=lambda: f"delta_{np.random.randint(1000000)}",
        description="Unique identifier for this delta"
    )
    proposed_by: str = Field(
        default="scientist",
        description="Agent that proposed this delta"
    )
    timestamp: str = Field(
        default_factory=lambda: "2026-09-01T00:00:00Z",
        description="Proposal timestamp"
    )
    hypothesis: str = Field(
        default="",
        description="Hypothesis behind this change"
    )
    
    # What to change
    # Each field is a path to the genome field to change, with the new value
    # Path format: "field.subfield[index].subsubfield"
    # Use None to delete, or provide the new value
    changes: Dict[str, Any] = Field(
        default_factory=dict,
        description="Dictionary of path -> new value (or None to delete)"
    )
    
    # Valid operations
    operation: str = Field(
        default="modify",
        description="Operation type: 'modify', 'add', 'delete', 'replace'"
    )
    
    def apply(self, genome: DevelopmentalGenome) -> DevelopmentalGenome:
        """
        Apply this delta to a genome, returning a new genome.
        
        This performs a deep copy and applies changes using the path notation.
        """
        # TODO: Implement path-based application
        # For now, return the original (stub implementation)
        return genome


# =============================================================================
# UTILITY FUNCTIONS
# =============================================================================

def create_minimal_genome(
    name: str = "minimal",
    n_neurons: int = 10000,
    n_inhibitory: int = 2000,
) -> DevelopmentalGenome:
    """
    Create a minimal genome for the MVE (Minimum Viable Experiment).
    
    Creates:
    - 2 neuron types: excitatory (LIF), inhibitory (LIF)
    - 2 populations: exc (8000), inh (2000)
    - 1 synapse type: STDP
    - 2 connectivity rules: exc->exc, exc->inh, inh->exc, inh->inh
    - 1 plasticity rule: STDP
    - Basic observables
    """
    # Neuron types
    neuron_types = [
        NeuronTypeSpec(
            name="excitatory",
            model=NeuronModel.LIF,
            tau_m=10.0,
            tau_ref=2.0,
            v_thresh=-50.0,
            v_reset=-70.0,
            v_rest=-70.0,
            e_rev=0.0,
            r=1.0,
            c=250.0,
            description="Excitatory LIF neuron"
        ),
        NeuronTypeSpec(
            name="inhibitory",
            model=NeuronModel.LIF,
            tau_m=8.0,
            tau_ref=1.5,
            v_thresh=-50.0,
            v_reset=-80.0,
            v_rest=-80.0,
            e_rev=-80.0,
            r=1.0,
            c=250.0,
            description="Inhibitory LIF neuron (faster, hyperpolarized)"
        ),
    ]
    
    # Synapse types
    synapse_types = [
        SynapseTypeSpec(
            name="stdp_exc",
            synapse_type=SynapseType.STD,
            weight=0.5,
            delay=1.0,
            tau_plus=20.0,
            tau_minus=20.0,
            a_plus=0.1,
            a_minus=0.1,
            w_min=0.0,
            w_max=2.0,
            description="STDP for excitatory synapses"
        ),
        SynapseTypeSpec(
            name="static_inh",
            synapse_type=SynapseType.STATIC,
            weight=-1.0,
            delay=0.5,
            description="Static inhibitory synapses"
        ),
    ]
    
    # Populations
    populations = [
        PopulationSpec(
            name="exc",
            neuron_type="excitatory",
            size=n_neurons - n_inhibitory,
            role="associative",
            noise_std=0.5,
            description="Excitatory population"
        ),
        PopulationSpec(
            name="inh",
            neuron_type="inhibitory",
            size=n_inhibitory,
            role="inhibitory",
            noise_std=0.5,
            description="Inhibitory population"
        ),
    ]
    
    # Connectivity rules
    connectivity_rules = [
        ConnectivityRule(
            name="exc_to_exc",
            source="exc",
            target="exc",
            pattern=ConnectivityPattern.SPARSE_RANDOM,
            probability=0.02,
            synapse_type="stdp_exc",
            weight_mean=0.5,
            weight_std=0.1,
            delay_mean=1.0,
            delay_std=0.5,
            allow_autapse=False,
            description="Excitatory to excitatory (sparse, plastic)"
        ),
        ConnectivityRule(
            name="exc_to_inh",
            source="exc",
            target="inh",
            pattern=ConnectivityPattern.SPARSE_RANDOM,
            probability=0.05,
            synapse_type="stdp_exc",
            weight_mean=0.8,
            weight_std=0.1,
            delay_mean=0.5,
            delay_std=0.2,
            description="Excitatory to inhibitory"
        ),
        ConnectivityRule(
            name="inh_to_exc",
            source="inh",
            target="exc",
            pattern=ConnectivityPattern.SPARSE_RANDOM,
            probability=0.05,
            synapse_type="static_inh",
            weight_mean=-1.5,
            weight_std=0.2,
            delay_mean=0.5,
            delay_std=0.2,
            description="Inhibitory to excitatory"
        ),
        ConnectivityRule(
            name="inh_to_inh",
            source="inh",
            target="inh",
            pattern=ConnectivityPattern.SPARSE_RANDOM,
            probability=0.02,
            synapse_type="static_inh",
            weight_mean=-1.0,
            weight_std=0.1,
            delay_mean=0.5,
            delay_std=0.2,
            description="Inhibitory to inhibitory"
        ),
    ]
    
    # Plasticity rules
    plasticity_rules = [
        PlasticityRule(
            name="stdp_rule",
            rule_type=PlasticityRuleType.STDP,
            applies_to=["stdp_exc"],
            tau_plus=20.0,
            tau_minus=20.0,
            a_plus=0.1,
            a_minus=0.1,
            w_min=0.0,
            w_max=2.0,
            pre_synaptic=True,
            post_synaptic=True,
            description="Standard STDP for excitatory synapses"
        ),
    ]
    
    # Observables
    observables = [
        ObservableSpec(
            name="exc_firing_rate",
            observable_type="firing_rate",
            source_population="exc",
            aggregation="mean",
            window_size=100.0,
            sample_rate=10.0,
            description="Mean firing rate of excitatory population"
        ),
        ObservableSpec(
            name="inh_firing_rate",
            observable_type="firing_rate",
            source_population="inh",
            aggregation="mean",
            window_size=100.0,
            sample_rate=10.0,
            description="Mean firing rate of inhibitory population"
        ),
        ObservableSpec(
            name="network_synchrony",
            observable_type="synchrony",
            aggregation="mean",
            window_size=100.0,
            sample_rate=10.0,
            description="Network-wide synchrony measure"
        ),
        ObservableSpec(
            name="exc_weight_mean",
            observable_type="plasticity_statistics",
            source_connection="exc_to_exc",
            aggregation="mean",
            window_size=1000.0,
            sample_rate=1.0,
            description="Mean weight of exc->exc synapses"
        ),
        ObservableSpec(
            name="topology_connectivity",
            observable_type="topology",
            aggregation="raw",
            window_size=10000.0,
            sample_rate=0.1,
            description="Network connectivity matrix snapshot"
        ),
    ]
    
    return DevelopmentalGenome(
        version="1.0",
        name=name,
        description=f"Minimal genome for MVE with {n_neurons} neurons",
        neuron_types=neuron_types,
        synapse_types=synapse_types,
        populations=populations,
        connectivity_rules=connectivity_rules,
        plasticity_rules=plasticity_rules,
        observables=observables,
        # Leave other fields at defaults
    )


if __name__ == "__main__":
    # Create and validate a minimal genome
    genome = create_minimal_genome(name="mve_v1", n_neurons=10000)
    
    # Validate by serializing/deserializing
    json_data = genome.to_dict()
    loaded_genome = DevelopmentalGenome.from_dict(json_data)
    
    print(f"Created minimal genome: {genome.name}")
    print(f"  Neuron types: {len(genome.neuron_types)}")
    print(f"  Synapse types: {len(genome.synapse_types)}")
    print(f"  Populations: {len(genome.populations)}")
    print(f"  Connectivity rules: {len(genome.connectivity_rules)}")
    print(f"  Plasticity rules: {len(genome.plasticity_rules)}")
    print(f"  Observables: {len(genome.observables)}")
    
    # Save to file
    genome.save("minimal_genome_v1.json")
    print(f"  Saved to minimal_genome_v1.json")
    
    # Test loading
    loaded = DevelopmentalGenome.load("minimal_genome_v1.json")
    print(f"  Loaded and validated: {loaded.name}")
