"""
Neuromorphic Co-Development Framework - Genome Compiler

Compiles a DevelopmentalGenome into a runnable Brian2 network.

This is the bridge between the LLM-editable genome and the neuromorphic
substrate implementation. The compiler is hardware-agnostic at the genome
level; this Brian2 implementation can be replaced with Lava or hardware
backends later.

Author: Generated by Mistral Vibe
Date: 2026-09-01
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any, Dict, List, Optional, Tuple
import numpy as np
import brian2 as b2

if TYPE_CHECKING:
    from genome_schema import (
        ConnectivityRule,
        ConnectivityPattern,
        DevelopmentalGenome,
        NeuronTypeSpec,
        PlasticityRule,
        PlasticityRuleType,
        PopulationSpec,
        SynapseTypeSpec,
        SynapseType,
    )


# =============================================================================
# COMPILER STATE (for tracking compiled networks)
# =============================================================================

class CompiledNetwork:
    """
    Container for a compiled Brian2 network.
    
    Holds all Brian2 objects, state trackers, and metadata needed
    to run and observe the network.
    """
    
    def __init__(self):
        # Brian2 groups and synapses
        self.neuron_groups: Dict[str, b2.NeuronGroup] = {}
        self.synapse_groups: Dict[str, b2.Synapses] = {}
        
        # State trackers
        self.spike_monitors: Dict[str, b2.SpikeMonitor] = {}
        self.state_monitors: Dict[str, b2.StateMonitor] = {}
        
        # Network metadata
        self.population_sizes: Dict[str, int] = {}
        self.connection_counts: Dict[str, int] = {}
        
        # Runtime state
        self.net: Optional[b2.Network] = None
        self.run_time: float = 0.0
        
        # Homeostatic / scheduled operations (added to the network at build time)
        self.network_operations: List[b2.NetworkOperation] = []
        
        # Observable values
        self.observable_cache: Dict[str, Any] = {}
        
        # Neuromodulator state (three-factor gating). ``neuromodulators`` holds
        # the genome's NeuromodulatorSpec list; ``neuromodulator_level`` is the
        # running dopamine gate D applied to THREE_FACTOR synapses.
        self.neuromodulators: List[Any] = []
        self.neuromodulator_level: float = 0.0
    
    def add_neuron_group(self, name: str, group: b2.NeuronGroup):
        """Register a neuron group."""
        self.neuron_groups[name] = group
        self.population_sizes[name] = len(group)
    
    def add_synapse_group(self, name: str, synapses: b2.Synapses):
        """Register a synapse group."""
        self.synapse_groups[name] = synapses
        self.connection_counts[name] = len(synapses)
    
    def add_spike_monitor(self, name: str, monitor: b2.SpikeMonitor):
        """Register a spike monitor."""
        self.spike_monitors[name] = monitor
    
    def add_state_monitor(self, name: str, monitor: b2.StateMonitor):
        """Register a state monitor."""
        self.state_monitors[name] = monitor
    
    def build_network(self):
        """Build the Brian2 Network container."""
        self.net = b2.Network()
        self.net.add(self.neuron_groups.values())
        self.net.add(self.synapse_groups.values())
        self.net.add(self.spike_monitors.values())
        self.net.add(self.state_monitors.values())
        self.net.add(self.network_operations)
    
    def run(self, duration: float, report: str = 'text'):
        """Run the network for a duration."""
        if self.net is None:
            self.build_network()
        
        self.net.run(duration * b2.ms, report=report)
        self.run_time += duration
    
    def reset_transient_state(self):
        """Reset transient activity state, preserving learned weights.

        Working memory operates on a faster timescale than plasticity: between
        trials the membrane potential and the slow currents should return to
        baseline while the STDP-shaped synaptic weights persist. Without this,
        the slow adaptation current (tau_adapt ~ hundreds of ms vs a ~700 ms
        trial) accumulates a floor across trials and biases the network toward
        the silent attractor state, degrading delay maintenance.
        """
        for group in self.neuron_groups.values():
            group.v = group.v_rest
            if 'g_nmda' in group.variables:
                group.g_nmda = 0 * b2.mV
            if 'g_adapt' in group.variables:
                group.g_adapt = 0 * b2.mV
    
    def set_neuromodulator_level(self, level: float) -> None:
        """Set the neuromodulator gate ``D`` on every three-factor synapse.

        ``D`` scales the STDP weight update by ``(1 + D)``, so a positive level
        (reward) reinforces plasticity and a negative level (punishment)
        suppresses it.
        """
        self.neuromodulator_level = float(level)
        for sg in self.synapse_groups.values():
            if 'D' in sg.variables:
                sg.D = self.neuromodulator_level
    
    def apply_reward(self, reward: float, elapsed_ms: float = 0.0) -> float:
        """Update the neuromodulator level in response to a trial outcome.

        For each neuromodulator, releases on reward (``trigger_on_reward``) or
        suppresses on error (``trigger_on_error``), then decays the level toward
        its baseline over ``elapsed_ms`` (the trial duration). Returns the new
        level so the harness can log it.
        """
        for nm in self.neuromodulators:
            baseline = getattr(nm, 'baseline', 0.0)
            release = getattr(nm, 'release_amount', 1.0)
            tau_decay = getattr(nm, 'tau_decay', None)
            trigger_reward = getattr(nm, 'trigger_on_reward', False)
            trigger_error = getattr(nm, 'trigger_on_error', False)

            # Decay toward baseline over the elapsed trial time.
            if tau_decay and elapsed_ms > 0.0:
                decay = float(np.exp(-elapsed_ms / tau_decay))
                self.neuromodulator_level = baseline + (self.neuromodulator_level - baseline) * decay

            # Release (reward) or suppress (error).
            if reward > 0.0 and trigger_reward:
                self.neuromodulator_level += release
            elif reward < 0.0 and trigger_error:
                self.neuromodulator_level -= release

        self.set_neuromodulator_level(self.neuromodulator_level)
        return self.neuromodulator_level
    
    def get_firing_rate(self, population: str, window: float = 100.0) -> float:
        """Get mean firing rate for a population over the last window ms."""
        if population not in self.spike_monitors:
            return 0.0
        
        monitor = self.spike_monitors[population]
        # Get spikes in the last window
        mask = (monitor.t / b2.ms) >= (self.run_time - window)
        n_spikes = np.sum(mask)
        n_neurons = self.population_sizes[population]
        
        if window <= 0:
            return 0.0
        
        return (n_spikes / n_neurons) / (window / 1000.0)  # Hz
    
    def get_mean_weight(self, connection_name: str) -> float:
        """Get mean weight for a synapse group."""
        if connection_name not in self.synapse_groups:
            return 0.0
        
        synapses = self.synapse_groups[connection_name]
        if len(synapses) == 0:
            return 0.0
        
        return np.mean(synapses.w)
    
    def get_spike_count(self, population: str) -> int:
        """Get total spike count for a population."""
        if population not in self.spike_monitors:
            return 0
        return len(self.spike_monitors[population].t)


# =============================================================================
# HELPER FUNCTIONS FOR CONNECTIVITY
# =============================================================================

def create_connectivity_matrix(
    source_size: int,
    target_size: int,
    pattern: ConnectivityPattern,
    probability: Optional[float] = None,
    k: Optional[int] = None,
    beta: Optional[float] = None,
    m: Optional[int] = None,
    allow_autapse: bool = False,
    rng: Optional[np.random.Generator] = None,
) -> np.ndarray:
    """
    Create a connectivity matrix based on the specified pattern.
    
    Args:
        source_size: Number of neurons in source population
        target_size: Number of neurons in target population
        pattern: Connectivity pattern type
        probability: Connection probability (for SPARSE_RANDOM)
        k: Number of neighbors (for SMALL_WORLD)
        beta: Rewiring probability (for SMALL_WORLD)
        m: Edges per new node (for SCALE_FREE)
        allow_autapse: Whether to allow self-connections
        rng: Random number generator
    
    Returns:
        Boolean connectivity matrix of shape (source_size, target_size)
    """
    from genome_schema import ConnectivityPattern

    if rng is None:
        rng = np.random.default_rng()
    
    if pattern == ConnectivityPattern.FULL:
        matrix = np.ones((source_size, target_size), dtype=bool)
        if not allow_autapse:
            np.fill_diagonal(matrix, False)
        return matrix
    
    elif pattern == ConnectivityPattern.SPARSE_RANDOM:
        if probability is None:
            raise ValueError("SPARSE_RANDOM requires probability parameter")
        matrix = rng.random((source_size, target_size)) < probability
        if not allow_autapse:
            np.fill_diagonal(matrix, False)
        return matrix
    
    elif pattern == ConnectivityPattern.SMALL_WORLD:
        if k is None or beta is None:
            raise ValueError("SMALL_WORLD requires k and beta parameters")
        # Create small-world network (Watts-Strogatz)
        # For simplicity, create a ring and rewire
        matrix = np.zeros((source_size, target_size), dtype=bool)
        
        # Only implement for square matrices
        if source_size == target_size:
            # Create ring connections
            for i in range(source_size):
                for j in range(1, k // 2 + 1):
                    idx1 = (i + j) % source_size
                    idx2 = (i - j) % source_size
                    matrix[i, idx1] = True
                    matrix[i, idx2] = True
            
            # Rewire with probability beta
            for i in range(source_size):
                for j in range(source_size):
                    if matrix[i, j] and i != j:
                        if rng.random() < beta:
                            # Rewire to random neuron
                            new_j = rng.integers(0, source_size)
                            while new_j == i or matrix[i, new_j]:
                                new_j = rng.integers(0, source_size)
                            matrix[i, j] = False
                            matrix[i, new_j] = True
        else:
            # Fall back to sparse random for non-square
            p = (k * 2) / target_size
            matrix = rng.random((source_size, target_size)) < p
        
        if not allow_autapse:
            np.fill_diagonal(matrix, False)
        return matrix
    
    elif pattern == ConnectivityPattern.ERDOS_RENYI:
        if probability is None:
            probability = 0.1  # Default
        return create_connectivity_matrix(
            source_size, target_size, ConnectivityPattern.SPARSE_RANDOM,
            probability=probability, allow_autapse=allow_autapse, rng=rng
        )
    
    elif pattern == ConnectivityPattern.GRID:
        # Create 2D grid connectivity
        # For now, fall back to sparse random
        if probability is None:
            probability = 0.05
        return create_connectivity_matrix(
            source_size, target_size, ConnectivityPattern.SPARSE_RANDOM,
            probability=probability, allow_autapse=allow_autapse, rng=rng
        )
    
    elif pattern == ConnectivityPattern.TORUS:
        # Similar to grid but with wrap-around
        if probability is None:
            probability = 0.05
        return create_connectivity_matrix(
            source_size, target_size, ConnectivityPattern.SPARSE_RANDOM,
            probability=probability, allow_autapse=allow_autapse, rng=rng
        )
    
    elif pattern == ConnectivityPattern.SCALE_FREE:
        # Barabasi-Albert scale-free network
        # For simplicity, use sparse random with power-law-ish distribution
        if probability is None:
            probability = 0.01
        return create_connectivity_matrix(
            source_size, target_size, ConnectivityPattern.SPARSE_RANDOM,
            probability=probability, allow_autapse=allow_autapse, rng=rng
        )
    
    else:
        # Default to sparse random
        if probability is None:
            probability = 0.02
        return create_connectivity_matrix(
            source_size, target_size, ConnectivityPattern.SPARSE_RANDOM,
            probability=probability, allow_autapse=allow_autapse, rng=rng
        )


# =============================================================================
# NEURON MODEL COMPILERS
# =============================================================================

def compile_lif_neuron(
    name: str,
    spec: NeuronTypeSpec,
    size: int,
    noise_std: float = 0.0,
) -> b2.NeuronGroup:
    """
    Compile a LIF neuron group from specification.
    
    Args:
        name: Name for the neuron group
        spec: Neuron type specification
        size: Number of neurons
        noise_std: Noise standard deviation
    
    Returns:
        Brian2 NeuronGroup
    """
    # LIF equations. v_rest/r/tau_m are declared as shared constants so they
    # can be assigned after construction (Brian2 does not infer undeclared names).
    #
    # If ``spec.tau_slow`` is set, the neuron also carries a slow NMDA-like
    # current ``g_nmda`` (units of volt) that decays with time constant
    # ``tau_slow``. Recurrent synapses compiled with ``slow_channel=True``
    # charge this current instead of ``v``, so a stimulus-elicited pattern can
    # be held across a delay (working memory; Wang 1999 / Compte et al. 2000).
    #
    # If ``spec.tau_adapt`` and ``spec.increment`` are set, the neuron also
    # carries a spike-frequency-adaptation current ``g_adapt`` (units of volt)
    # that steps up by ``increment`` mV on every spike and decays with time
    # constant ``tau_adapt``. Adaptation is the slow *negative* feedback that
    # balances the slow NMDA *positive* feedback, turning the otherwise
    # collapse-or-runaway recurrent network into a bistable attractor that can
    # hold a moderate firing rate through a delay (Compte et al. 2000).
    tau_slow = getattr(spec, 'tau_slow', None)
    has_slow = tau_slow not in (None, 0.0)
    tau_adapt = getattr(spec, 'tau_adapt', None)
    increment = getattr(spec, 'increment', None)
    has_adapt = tau_adapt not in (None, 0.0)

    drive = "r * I"
    slow_line = ""
    adapt_line = ""
    if has_slow:
        drive += " + g_nmda"
        slow_line = f"    dg_nmda/dt = -g_nmda / ({float(tau_slow)} * ms) : volt\n"
    if has_adapt:
        drive += " - g_adapt"
        adapt_line = f"    dg_adapt/dt = -g_adapt / ({float(tau_adapt)} * ms) : volt\n"

    noise_term = ""
    method = 'exact'
    if noise_std > 0:
        # Add Gaussian white membrane-potential noise of amplitude noise_std (mV).
        noise_term = f" + ({noise_std} * mV) * xi * tau_m**-0.5"
        method = 'euler'

    eqs = f'''
    dv/dt = (v_rest - v + {drive}) / tau_m{noise_term} : volt (unless refractory)
{slow_line}{adapt_line}    v_rest : volt (shared)
    r : ohm (shared)
    tau_m : second (shared)
    I : amp
    '''

    reset = f'v = {spec.v_reset} * mV'
    if has_adapt:
        reset += f'\n    g_adapt += {float(increment)} * mV'

    group = b2.NeuronGroup(
        size,
        eqs,
        method=method,
        refractory=f'{spec.tau_ref} * ms',
        threshold=f'v > {spec.v_thresh} * mV',
        reset=reset,
        name=name,
    )
    
    # Set initial values and constant parameters
    group.v = f'{spec.v_rest} * mV'
    group.v_rest = f'{spec.v_rest} * mV'
    group.r = f'{spec.r} * Mohm'
    group.tau_m = f'{spec.tau_m} * ms'
    group.I = '0 * amp'
    if has_slow:
        group.g_nmda = '0 * mV'
    if has_adapt:
        group.g_adapt = '0 * mV'
    
    return group


def compile_adaptive_lif_neuron(
    name: str,
    spec: NeuronTypeSpec,
    size: int,
    noise_std: float = 0.0,
) -> b2.NeuronGroup:
    """
    Compile an Adaptive LIF neuron group from specification.
    """
    eqs = '''
    dv/dt = (v_rest - v + r * I - w) / tau_m : volt (unless refractory)
    dw/dt = (a - w) / tau_adapt : amp
    a : amp
    I : amp
    '''
    
    if noise_std > 0:
        eqs += f'''
    xi : 1
    I_noise = {noise_std} * mV * xi : amp
    I = I + I_noise
    '''
    
    # Calculate 'a' parameter for adaptation
    # w increases by 'increment' per spike, decays with tau_adapt
    # At steady state: a = increment * firing_rate
    # For now, set a to 0 and handle adaptation through reset
    
    group = b2.NeuronGroup(
        size,
        eqs,
        method='exact',
        refractory=f'{spec.tau_ref} * ms',
        threshold=f'v > {spec.v_thresh} * mV',
        reset=f'''
        v = {spec.v_reset} * mV
        w = w + {spec.increment} * mV
        ''',
        name=name,
    )
    
    group.v = f'{spec.v_rest} * mV'
    group.w = '0 * mV'
    group.a = '0 * amp'
    
    return group


def compile_neuron_group(
    name: str,
    spec: NeuronTypeSpec,
    size: int,
    noise_std: float = 0.0,
) -> b2.NeuronGroup:
    """
    Compile a neuron group based on the neuron type specification.
    
    Dispatches to the appropriate compiler based on the model type.
    """
    from genome_schema import NeuronModel
    
    if spec.model == NeuronModel.LIF:
        return compile_lif_neuron(name, spec, size, noise_std)
    elif spec.model == NeuronModel.ADAPTIVE_LIF:
        return compile_adaptive_lif_neuron(name, spec, size, noise_std)
    else:
        # Fall back to LIF for unsupported models
        print(f"Warning: Neuron model {spec.model} not yet implemented. Falling back to LIF.")
        return compile_lif_neuron(name, spec, size, noise_std)


# =============================================================================
# SYNAPSE COMPILERS
# =============================================================================

def compile_static_synapses(
    source: b2.NeuronGroup,
    target: b2.NeuronGroup,
    spec: SynapseTypeSpec,
    connectivity: np.ndarray,
    name: str,
) -> b2.Synapses:
    """
    Compile static (non-plastic) synapses.

    Connectivity is applied explicitly via ``S.connect``, and the weight is
    stored in a per-synapse ``w`` state variable so it is observable through
    ``get_mean_weight``.
    """
    # Get pre and post indices from connectivity matrix
    pre_idx, post_idx = np.where(connectivity)

    # ``slow_channel`` routes the EPSP into the target's slow NMDA-like current
    # (working-memory maintenance) instead of its membrane potential.
    post_var = 'g_nmda' if getattr(spec, 'slow_channel', False) else 'v'

    S = b2.Synapses(
        source,
        target,
        'w : 1',
        on_pre=f'{post_var}_post += w * mV',
        delay=spec.delay * b2.ms,
        name=name,
    )

    # Set connectivity and initial weight
    S.connect(i=pre_idx, j=post_idx)
    S.w = spec.weight

    return S


# Shared pair-based STDP model. ``apre``/``apost`` are event-driven traces that
# decay between spikes; the weight is potentiated on postsynaptic spikes
# (pre-before-post) and depressed on presynaptic spikes (post-before-pre).
STDP_MODEL = '''
w : 1
tau_plus : second
tau_minus : second
a_plus : 1
a_minus : 1
w_min : 1
w_max : 1
dapre/dt = -apre/tau_plus : 1 (event-driven)
dapost/dt = -apost/tau_minus : 1 (event-driven)
'''

STDP_ON_PRE = '''
v_post += w * mV
apre += 1
w = clip(w - a_minus * apost, w_min, w_max)
'''

STDP_ON_POST = '''
apost += 1
w = clip(w + a_plus * apre, w_min, w_max)
'''

# Three-factor (neuromodulator-gated) STDP: identical pair-based STDP, but the
# plasticity update is scaled by ``(1 + D)`` where ``D`` is a neuromodulator
# scalar (e.g. the dopamine level). ``D == 0`` recovers plain STDP. Ported from
# the earlier ``legacy_vibe_web/compiler.py``.
THREE_FACTOR_MODEL = STDP_MODEL + '''
D : 1 (shared)
'''

THREE_FACTOR_ON_PRE = '''
v_post += w * mV
apre += 1
w = clip(w - a_minus * apost * (1.0 + D), w_min, w_max)
'''

THREE_FACTOR_ON_POST = '''
apost += 1
w = clip(w + a_plus * apre * (1.0 + D), w_min, w_max)
'''

THREE_FACTOR_SLOW_ON_PRE = '''
v_post += w * mV
g_nmda_post += w * mV
apre += 1
w = clip(w - a_minus * apost * (1.0 + D), w_min, w_max)
'''


def _neuromodulator_level(genome: 'DevelopmentalGenome') -> float:
    """Return the dopamine baseline (or 0.0) as the three-factor gate ``D``."""
    for nm in genome.neuromodulators:
        if nm.name == "dopamine":
            return nm.baseline
    if genome.neuromodulators:
        return genome.neuromodulators[0].baseline
    return 0.0


def compile_stdp_synapses(
    source: b2.NeuronGroup,
    target: b2.NeuronGroup,
    spec: SynapseTypeSpec,
    connectivity: np.ndarray,
    name: str,
    neuromodulator_level: float = 0.0,
) -> b2.Synapses:
    """
    Compile pair-based STDP synapses (optionally three-factor / neuromodulated).

    Uses event-driven presynaptic (``apre``) and postsynaptic (``apost``)
    traces. On a postsynaptic spike the weight is potentiated by
    ``a_plus * apre`` (pre-before-post); on a presynaptic spike it is depressed
    by ``a_minus * apost`` (post-before-pre). Weights are clipped to
    ``[w_min, w_max]``.

    If ``spec.synapse_type`` is ``THREE_FACTOR``, the plasticity update is
    gated by ``(1 + D)`` where ``D = neuromodulator_level`` (the dopamine
    level), so a reward signal scales how strongly STDP acts.
    """
    from genome_schema import SynapseType

    three_factor = spec.synapse_type == SynapseType.THREE_FACTOR

    # Get pre and post indices from connectivity matrix
    pre_idx, post_idx = np.where(connectivity)

    # Fall back to sensible defaults for any unset STDP parameters.
    tau_plus = spec.tau_plus if spec.tau_plus is not None else 20.0
    tau_minus = spec.tau_minus if spec.tau_minus is not None else 20.0
    a_plus = spec.a_plus if spec.a_plus is not None else 0.01
    a_minus = spec.a_minus if spec.a_minus is not None else 0.01
    w_min = spec.w_min if spec.w_min is not None else 0.0
    w_max = spec.w_max if spec.w_max is not None else 2.0

    # Recurrent working-memory synapses drive BOTH a fast AMPA-like component
    # (the membrane potential ``v``) and a slow NMDA-like component
    # (``g_nmda``). The fast component is what lets feedback inhibition balance
    # the recurrence at the membrane level; the slow component is what holds a
    # remembered pattern across the delay. A purely-slow recurrent synapse
    # cannot be balanced by fast inhibition and collapses to silence or runs
    # away. See [[Neuromorphic_Homeostasis_Implementation]].
    if three_factor:
        model = THREE_FACTOR_MODEL
        on_post = THREE_FACTOR_ON_POST
        on_pre = THREE_FACTOR_SLOW_ON_PRE if getattr(spec, 'slow_channel', False) else THREE_FACTOR_ON_PRE
    else:
        model = STDP_MODEL
        on_post = STDP_ON_POST
        if getattr(spec, 'slow_channel', False):
            on_pre = '''
v_post += w * mV
g_nmda_post += w * mV
apre += 1
w = clip(w - a_minus * apost, w_min, w_max)
'''
        else:
            on_pre = STDP_ON_PRE

    S = b2.Synapses(
        source,
        target,
        model,
        on_pre=on_pre,
        on_post=on_post,
        delay=spec.delay * b2.ms,
        name=name,
    )

    # Set connectivity and initial state
    S.connect(i=pre_idx, j=post_idx)
    S.w = spec.weight
    S.tau_plus = tau_plus * b2.ms
    S.tau_minus = tau_minus * b2.ms
    S.a_plus = a_plus
    S.a_minus = a_minus
    S.w_min = w_min
    S.w_max = w_max
    if three_factor:
        S.D = neuromodulator_level

    return S


def compile_synapses(
    source: b2.NeuronGroup,
    target: b2.NeuronGroup,
    synapse_spec: SynapseTypeSpec,
    connectivity: np.ndarray,
    name: str,
    neuromodulator_level: float = 0.0,
) -> b2.Synapses:
    """
    Compile synapses based on the synapse type specification.
    
    Dispatches to the appropriate compiler based on synapse_type.
    """
    from genome_schema import SynapseType
    
    if synapse_spec.synapse_type in [SynapseType.STATIC, SynapseType.HEBBIAN]:
        return compile_static_synapses(source, target, synapse_spec, connectivity, name)
    elif synapse_spec.synapse_type in [SynapseType.STD, SynapseType.THREE_FACTOR]:
        return compile_stdp_synapses(source, target, synapse_spec, connectivity, name, neuromodulator_level)
    else:
        print(f"Warning: Synapse type {synapse_spec.synapse_type} not yet implemented. Falling back to static.")
        return compile_static_synapses(source, target, synapse_spec, connectivity, name)


# =============================================================================
# PLASTICITY RULE COMPILERS
# =============================================================================

def apply_plasticity_rule(
    synapses: b2.Synapses,
    rule: PlasticityRule,
) -> None:
    """
    Apply a plasticity rule to a synapse group.
    
    This modifies the synapse group to include the plasticity dynamics.
    """
    from genome_schema import PlasticityRuleType
    
    if rule.rule_type == PlasticityRuleType.STDP:
        # STDP is handled in the synapse compilation
        # For now, just ensure the parameters are set
        pass
    elif rule.rule_type == PlasticityRuleType.TRIPLET_STDP:
        # Triplet STDP implementation
        pass
    elif rule.rule_type == PlasticityRuleType.HOMEOSTATIC:
        # Homeostatic plasticity
        pass
    else:
        print(f"Warning: Plasticity rule type {rule.rule_type} not yet implemented.")


# =============================================================================
# HOMEOSTATIC RULE COMPILERS
# =============================================================================

def _read_weight_bounds(synapses: b2.Synapses) -> Tuple[float, float]:
    """Return (w_min, w_max) for a plastic synapse group, else (0.0, inf)."""
    w_min, w_max = 0.0, float("inf")
    if len(synapses) == 0:
        return w_min, w_max
    if "w_min" in synapses.variables:
        w_min = float(np.min(np.asarray(synapses.w_min)))
    if "w_max" in synapses.variables:
        w_max = float(np.max(np.asarray(synapses.w_max)))
    return w_min, w_max


def _normalize_incoming_weights(
    synapses: b2.Synapses,
    target_sums: np.ndarray,
    w_min: float = 0.0,
    w_max: float = float("inf"),
) -> None:
    """
    Rescale each post-synaptic neuron's incoming weights so their sum returns
    to ``target_sums[j]`` (multiplicative synaptic scaling, Turrigiano 1998).

    The relative weight structure that fast plasticity (STDP) shaped is
    preserved; only the global drift (runaway depression/potentiation) is
    removed. Weights are re-clipped to ``[w_min, w_max]`` so this agrees with
    the plasticity bounds.
    """
    if len(synapses) == 0:
        return
    w = np.asarray(synapses.w, dtype=float)
    j = np.asarray(synapses.j, dtype=int)
    n_post = len(synapses.target)
    sums = np.bincount(j, weights=w, minlength=n_post)
    scale = np.ones(n_post, dtype=float)
    nz = sums > 1e-12
    scale[nz] = target_sums[nz] / sums[nz]
    # Bound the per-step rescaling factor for numerical stability.
    scale = np.clip(scale, 1e-3, 1e3)
    w = w * scale[j]
    if w_min > 0.0 or np.isfinite(w_max):
        w = np.clip(w, w_min, w_max)
    synapses.w = w


def _make_weight_normalization_operation(
    synapses: b2.Synapses,
    interval_ms: float,
    name: str,
) -> b2.NetworkOperation:
    """
    Build a scheduled operation that normalizes ``synapses`` every
    ``interval_ms`` ms of simulated time.

    The target is each neuron's *initial* incoming weight sum, captured before
    simulation. This holds the network's recurrent drive at its starting point
    while STDP reshapes the distribution of individual weights.
    """
    w0 = np.asarray(synapses.w, dtype=float)
    j0 = np.asarray(synapses.j, dtype=int)
    target_sums = np.bincount(j0, weights=w0, minlength=len(synapses.target))
    w_min, w_max = _read_weight_bounds(synapses)

    def _normalize() -> None:
        _normalize_incoming_weights(synapses, target_sums, w_min=w_min, w_max=w_max)

    return b2.NetworkOperation(
        _normalize,
        dt=interval_ms * b2.ms,
        name=name,
    )


def apply_homeostatic_rule(
    compiled: CompiledNetwork,
    rule: Any,
) -> None:
    """
    Apply a ``HomeostaticRule`` to a compiled network.

    Supported mechanisms (see [[Neuromorphic_Homeostasis_Implementation]]):

    - ``WEIGHT_NORMALIZATION``: keep each post-synaptic neuron's incoming
      weight sum at its initial value, on a slow clock. ``applies_to`` names the
      connection (synapse group) to normalize.
    """
    from genome_schema import HomeostaticMechanism

    interval_ms = rule.apply_interval if rule.apply_interval is not None else 100.0

    if rule.mechanism == HomeostaticMechanism.WEIGHT_NORMALIZATION:
        for name in rule.applies_to:
            if name not in compiled.synapse_groups:
                print(
                    f"Warning: homeostatic rule '{rule.name}' references "
                    f"unknown connection '{name}'; skipping."
                )
                continue
            op = _make_weight_normalization_operation(
                compiled.synapse_groups[name],
                interval_ms=interval_ms,
                name=f"homeo_{rule.name}_{name}",
            )
            compiled.network_operations.append(op)
    else:
        print(
            f"Warning: homeostatic mechanism '{rule.mechanism}' "
            f"not yet implemented."
        )


# =============================================================================
# MAIN COMPILER
# =============================================================================

class GenomeCompiler:
    """
    Compiles a DevelopmentalGenome into a Brian2 network.
    
    This is the main class that orchestrates the compilation process.
    """
    
    def __init__(self, seed: Optional[int] = None):
        """
        Initialize the compiler.
        
        Args:
            seed: Random seed for reproducibility
        """
        self.seed = seed
        self.rng = np.random.default_rng(seed)
        
    def compile(self, genome: 'DevelopmentalGenome') -> CompiledNetwork:
        """
        Compile a genome into a Brian2 network.
        
        Args:
            genome: The developmental genome to compile
        
        Returns:
            CompiledNetwork containing all Brian2 objects
        """
        compiled = CompiledNetwork()
        
        # Step 1: Create neuron groups
        print("Compiling neuron populations...")
        neuron_groups = {}
        for pop_spec in genome.populations:
            neuron_type = genome.get_neuron_type(pop_spec.neuron_type)
            if neuron_type is None:
                raise ValueError(f"Neuron type '{pop_spec.neuron_type}' not found")
            
            group = compile_neuron_group(
                name=pop_spec.name,
                spec=neuron_type,
                size=pop_spec.size,
                noise_std=pop_spec.noise_std,
            )
            neuron_groups[pop_spec.name] = group
            compiled.add_neuron_group(pop_spec.name, group)
            
            # Add spike monitor for this population
            spike_mon = b2.SpikeMonitor(group, name=f"spike_mon_{pop_spec.name}")
            compiled.add_spike_monitor(pop_spec.name, spike_mon)
        
        # Step 2: Create connectivity
        print("Compiling connectivity...")
        neuromodulator_level = _neuromodulator_level(genome)
        for conn_spec in genome.connectivity_rules:
            source_group = neuron_groups[conn_spec.source]
            target_group = neuron_groups[conn_spec.target]
            
            synapse_type = genome.get_synapse_type(conn_spec.synapse_type)
            if synapse_type is None:
                raise ValueError(f"Synapse type '{conn_spec.synapse_type}' not found")
            
            # Create connectivity matrix
            connectivity = create_connectivity_matrix(
                source_size=len(source_group),
                target_size=len(target_group),
                pattern=conn_spec.pattern,
                probability=conn_spec.probability,
                k=conn_spec.k,
                beta=conn_spec.beta,
                m=conn_spec.m,
                allow_autapse=conn_spec.allow_autapse,
                rng=self.rng,
            )
            
            # Compile synapses
            synapses = compile_synapses(
                source=source_group,
                target=target_group,
                synapse_spec=synapse_type,
                connectivity=connectivity,
                name=conn_spec.name,
                neuromodulator_level=neuromodulator_level,
            )
            compiled.add_synapse_group(conn_spec.name, synapses)
        
        # Step 3: Apply plasticity rules
        print("Applying plasticity rules...")
        for rule in genome.plasticity_rules:
            for syn_name in rule.applies_to:
                if syn_name in compiled.synapse_groups:
                    apply_plasticity_rule(
                        compiled.synapse_groups[syn_name],
                        rule,
                    )

        # Step 3.5: Apply homeostatic rules (slow-timescale stabilizers)
        print("Applying homeostatic rules...")
        for rule in genome.homeostatic_rules:
            apply_homeostatic_rule(compiled, rule)

        # Step 4: Build network
        compiled.build_network()
        
        print(f"Compilation complete: {sum(compiled.population_sizes.values())} neurons, {sum(compiled.connection_counts.values())} connections")
        
        # Store neuromodulator config and the initial gate level so the harness
        # can drive reward-gated (three-factor) plasticity at runtime.
        compiled.neuromodulators = list(genome.neuromodulators)
        compiled.neuromodulator_level = neuromodulator_level
        
        return compiled


# =============================================================================
# SIMPLE STDP IMPLEMENTATION (for MVE)
# =============================================================================

def create_simple_stdp_network(
    n_exc: int = 8000,
    n_inh: int = 2000,
    conn_prob: float = 0.02,
    w_exc: float = 0.5,
    w_inh: float = -1.0,
    stdp_enabled: bool = True,
    a_plus: float = 0.1,
    a_minus: float = 0.1,
    tau_plus: float = 20.0,
    tau_minus: float = 20.0,
) -> CompiledNetwork:
    """
    Create a simple STDP network for the MVE.
    
    This is a convenience function that bypasses the full genome
    for quick testing.
    """
    compiled = CompiledNetwork()
    
    # Neuron models
    eqs = '''
    dv/dt = (v_rest - v + r * I) / tau_m : volt (unless refractory)
    v_rest : volt (shared)
    r : ohm (shared)
    tau_m : second (shared)
    I : amp
    '''
    
    # Excitatory population
    exc = b2.NeuronGroup(
        n_exc,
        eqs,
        method='exact',
        refractory='2 * ms',
        threshold='v > -50 * mV',
        reset='v = -70 * mV',
        name='exc',
    )
    exc.v = '-70 * mV'
    exc.I = '0 * amp'
    exc.tau_m = '10 * ms'
    exc.r = '1 * Mohm'
    exc.v_rest = '-70 * mV'
    
    # Inhibitory population
    inh = b2.NeuronGroup(
        n_inh,
        eqs,
        method='exact',
        refractory='1.5 * ms',
        threshold='v > -50 * mV',
        reset='v = -80 * mV',
        name='inh',
    )
    inh.v = '-80 * mV'
    inh.I = '0 * amp'
    inh.tau_m = '8 * ms'
    inh.r = '1 * Mohm'
    inh.v_rest = '-80 * mV'
    
    compiled.add_neuron_group('exc', exc)
    compiled.add_neuron_group('inh', inh)
    
    # Spike monitors
    exc_mon = b2.SpikeMonitor(exc, name='exc_spikes')
    inh_mon = b2.SpikeMonitor(inh, name='inh_spikes')
    compiled.add_spike_monitor('exc', exc_mon)
    compiled.add_spike_monitor('inh', inh_mon)
    
    # Add noise
    # For now, skip noise to make STDP effects clearer
    
    # Connectivity
    # exc -> exc (STDP)
    if stdp_enabled:
        S_ee = b2.Synapses(
            exc, exc,
            STDP_MODEL,
            on_pre=STDP_ON_PRE,
            on_post=STDP_ON_POST,
            delay=1.0 * b2.ms,
            name='exc_to_exc',
        )
        S_ee.connect(p=conn_prob)
        S_ee.w = w_exc
        S_ee.tau_plus = tau_plus * b2.ms
        S_ee.tau_minus = tau_minus * b2.ms
        S_ee.a_plus = a_plus
        S_ee.a_minus = a_minus
        S_ee.w_min = 0.0
        S_ee.w_max = 2.0
        compiled.add_synapse_group('exc_to_exc', S_ee)
    else:
        S_ee = b2.Synapses(exc, exc, 'w : 1', on_pre='v_post += w * mV', delay=1.0 * b2.ms, name='exc_to_exc')
        S_ee.connect(p=conn_prob)
        S_ee.w = w_exc
        compiled.add_synapse_group('exc_to_exc', S_ee)
    
    # exc -> inh
    S_ei = b2.Synapses(exc, inh, on_pre=f'v_post += {w_exc * 0.8} * mV', delay=0.5 * b2.ms, name='exc_to_inh')
    S_ei.connect(p=conn_prob * 2)
    compiled.add_synapse_group('exc_to_inh', S_ei)
    
    # inh -> exc
    S_ie = b2.Synapses(inh, exc, on_pre=f'v_post += {w_inh * 1.5} * mV', delay=0.5 * b2.ms, name='inh_to_exc')
    S_ie.connect(p=conn_prob * 2)
    compiled.add_synapse_group('inh_to_exc', S_ie)
    
    # inh -> inh
    S_ii = b2.Synapses(inh, inh, on_pre=f'v_post += {w_inh} * mV', delay=0.5 * b2.ms, name='inh_to_inh')
    S_ii.connect(p=conn_prob)
    compiled.add_synapse_group('inh_to_inh', S_ii)
    
    # Build network
    compiled.build_network()
    
    return compiled


# =============================================================================
# EXPORT
# =============================================================================

__all__ = [
    'GenomeCompiler',
    'CompiledNetwork',
    'create_simple_stdp_network',
]


if __name__ == "__main__":
    # Test compilation
    from genome_schema import create_minimal_genome
    
    print("Creating minimal genome...")
    genome = create_minimal_genome(name="test_compile", n_neurons=1000, n_inhibitory=200)
    
    print("Compiling genome...")
    compiler = GenomeCompiler(seed=42)
    network = compiler.compile(genome)
    
    print("Running network for 100ms...")
    network.run(duration=100.0, report='text')
    
    print("Results:")
    print(f"  Exc spikes: {network.get_spike_count('exc')}")
    print(f"  Inh spikes: {network.get_spike_count('inh')}")
    print(f"  Exc firing rate: {network.get_firing_rate('exc'):.2f} Hz")
    print(f"  Inh firing rate: {network.get_firing_rate('inh'):.2f} Hz")
    
    # Test simple STDP network
    print("\nCreating simple STDP network...")
    simple_net = create_simple_stdp_network(
        n_exc=1000,
        n_inh=200,
        conn_prob=0.05,
        stdp_enabled=True,
        a_plus=0.1,
        a_minus=0.1,
    )
    
    print("Running simple network for 100ms...")
    simple_net.run(duration=100.0, report='text')
    
    print("Results:")
    print(f"  Exc spikes: {simple_net.get_spike_count('exc')}")
    print(f"  Inh spikes: {simple_net.get_spike_count('inh')}")
