"""
Neuromorphic Co-Development Framework - DMS Task Genome

Sample genome for the delayed match-to-sample (DMS) seed task.

This genome defines a network with:
- 1000 sensory neurons (10 features × 100 neurons each)
- 8000 associative neurons (working memory)
- 2000 inhibitory neurons (stabilization)

Architecture follows the specification in seed_task_spec.md

Author: Generated by Mistral Vibe
Date: 2026-09-01
"""

from genome_schema import (
    ConnectivityPattern,
    ConnectivityRule,
    DevelopmentalGenome,
    HomeostaticMechanism,
    HomeostaticRule,
    NeuromodulatorSpec,
    NeuromodulatorType,
    NeuronModel,
    NeuronTypeSpec,
    ObservableSpec,
    PlasticityRule,
    PlasticityRuleType,
    PopulationSpec,
    SynapseType,
    SynapseTypeSpec,
)


def create_dms_genome(
    name: str = "dms_v1",
    n_features: int = 10,
    n_neurons_per_feature: int = 100,
    n_associative: int = 8000,
    n_inhibitory: int = 2000,
) -> DevelopmentalGenome:
    """
    Create a genome for the delayed match-to-sample task.
    
    Args:
        name: Genome name
        n_features: Number of sensory features
        n_neurons_per_feature: Neurons per feature in sensory layer
        n_associative: Number of associative neurons
        n_inhibitory: Number of inhibitory neurons
    
    Returns:
        DevelopmentalGenome configured for DMS task
    """
    
    # =========================================================================
    # NEURON TYPES
    # =========================================================================
    
    neuron_types = [
        # Sensory neurons - fast, responsive
        NeuronTypeSpec(
            name="sensory",
            model=NeuronModel.LIF,
            tau_m=5.0,      # Faster membrane time constant
            tau_ref=1.0,
            v_thresh=-50.0,
            v_reset=-70.0,
            v_rest=-70.0,
            e_rev=0.0,
            r=1.0,
            c=200.0,       # Lower capacitance = faster
            description="Fast LIF neuron for sensory encoding"
        ),
        
        # Associative neurons - standard
        NeuronTypeSpec(
            name="associative",
            model=NeuronModel.LIF,
            tau_m=10.0,
            tau_ref=2.0,
            v_thresh=-50.0,
            v_reset=-70.0,
            v_rest=-70.0,
            e_rev=0.0,
            r=1.0,
            c=250.0,
            tau_slow=100.0,  # NMDA-like current for delay-period maintenance
            tau_adapt=200.0,  # spike-frequency adaptation: slow negative feedback
            increment=0.2,    # adaptation step (mV) per spike
            description="LIF neuron for associative memory"
        ),
        
        # Inhibitory neurons - fast, hyperpolarizing
        NeuronTypeSpec(
            name="inhibitory",
            model=NeuronModel.LIF,
            tau_m=5.0,       # Fast
            tau_ref=1.0,
            v_thresh=-50.0,
            v_reset=-85.0,   # More hyperpolarized
            v_rest=-85.0,
            e_rev=-85.0,     # Inhibitory reversal potential
            r=1.0,
            c=200.0,
            description="Fast inhibitory LIF neuron"
        ),
    ]
    
    # =========================================================================
    # SYNAPSE TYPES
    # =========================================================================
    
    synapse_types = [
        # Sensory to associative - strong, static, selective.
        #
        # Selectivity lives in the *connectivity* (sparse random), not the
        # weight: with FULL homogeneous projections every associative neuron
        # receives the same total drive regardless of which feature is ON, so
        # the layer cannot encode stimulus identity. A sparse random projection
        # instead gives each associative neuron a distinct subset of sensory
        # inputs, so different stimuli recruit different neurons.
        #
        # The weight is raised from 2.0 to 10.0 mV because a sparse projection
        # delivers far fewer EPSPs per neuron; at 2.0 mV the associative layer
        # was never driven past threshold (0 Hz in response to a single ON
        # feature). See [[Neuromorphic_Homeostasis_Implementation]].
        SynapseTypeSpec(
            name="sensory_to_associative",
            synapse_type=SynapseType.STATIC,
            weight=10.0,       # Strong enough that sparse-selected neurons fire
            delay=1.0,
            description="Static synapse from sensory to associative (selective)"
        ),
        
        # Associative to associative - plastic, reward-gated (three-factor) STDP.
        #
        # Three-factor STDP gates the pair-based weight update by (1 + D), where
        # D is the dopamine level released on reward. A correct trial releases
        # dopamine (reinforcing the recurrent traces that held the sample) and
        # an incorrect trial suppresses it, so the attractor is shaped by the
        # outcome rather than eroded by unsupervised STDP.
        SynapseTypeSpec(
            name="assoc_to_assoc",
            synapse_type=SynapseType.THREE_FACTOR,
            weight=0.5,
            delay=1.5,
            tau_plus=20.0,
            tau_minus=20.0,
            a_plus=0.1,
            a_minus=0.1,
            w_min=0.01,
            w_max=2.0,
            neuromodulator="dopamine",  # gated by the reward signal
            slow_channel=True,  # recurrent excitation sustains delay activity
            description="Reward-gated (three-factor) STDP for associative plasticity"
        ),
        
        # Associative to inhibitory - plastic
        SynapseTypeSpec(
            name="assoc_to_inh",
            synapse_type=SynapseType.STD,
            weight=0.8,
            delay=1.0,
            tau_plus=20.0,
            tau_minus=20.0,
            a_plus=0.05,
            a_minus=0.05,
            w_min=0.01,
            w_max=1.0,
            description="STDP synapse from associative to inhibitory"
        ),
        
        # Inhibitory to associative - static, inhibitory
        SynapseTypeSpec(
            name="inh_to_assoc",
            synapse_type=SynapseType.STATIC,
            weight=-1.5,
            delay=0.5,
            description="Static inhibitory synapse"
        ),
        
        # Inhibitory to inhibitory - static, inhibitory
        SynapseTypeSpec(
            name="inh_to_inh",
            synapse_type=SynapseType.STATIC,
            weight=-1.0,
            delay=0.5,
            description="Static inhibitory synapse (inhibitory to inhibitory)"
        ),
    ]
    
    # =========================================================================
    # POPULATIONS
    # =========================================================================
    
    populations = [
        # Sensory layer - one population per feature
        *[
            PopulationSpec(
                name=f"sensory_f{i}",
                neuron_type="sensory",
                size=n_neurons_per_feature,
                role="sensory",
                noise_std=0.0,  # No noise for clean encoding
                description=f"Sensory population for feature {i}"
            )
            for i in range(n_features)
        ],
        
        # Associative layer
        PopulationSpec(
            name="associative",
            neuron_type="associative",
            size=n_associative,
            role="associative_memory",
            noise_std=0.1,  # Small noise for spontaneity
            description="Associative memory population with recurrent connectivity"
        ),
        
        # Inhibitory layer
        PopulationSpec(
            name="inhibitory",
            neuron_type="inhibitory",
            size=n_inhibitory,
            role="stabilization",
            noise_std=0.1,
            description="Inhibitory population for network stabilization"
        ),
    ]
    
    # =========================================================================
    # CONNECTIVITY RULES
    # =========================================================================
    
    # Sensory to associative - each feature population connects sparsely to the
    # associative layer, so different features recruit different associative
    # neurons (stimulus-identity code). A FULL projection would collapse every
    # feature onto the same total drive, leaving the layer unable to tell
    # stimuli apart.
    sensory_to_assoc_rules = []
    for i in range(n_features):
        sensory_to_assoc_rules.append(
            ConnectivityRule(
                name=f"sensory_f{i}_to_assoc",
                source=f"sensory_f{i}",
                target="associative",
                pattern=ConnectivityPattern.SPARSE_RANDOM,
                probability=0.2,
                synapse_type="sensory_to_associative",
                weight_mean=10.0,
                weight_std=0.0,
                delay_mean=1.0,
                delay_std=0.0,
                allow_autapse=False,
                description=f"Sparse selective connectivity from sensory feature {i} to associative"
            )
        )
    
    # Associative to associative - sparse, plastic
    assoc_rules = [
        ConnectivityRule(
            name="assoc_to_assoc",
            source="associative",
            target="associative",
            pattern=ConnectivityPattern.SPARSE_RANDOM,
            probability=0.02,
            synapse_type="assoc_to_assoc",
            weight_mean=0.5,
            weight_std=0.1,
            delay_mean=1.5,
            delay_std=0.5,
            allow_autapse=False,
            description="Sparse recurrent connectivity with STDP plasticity"
        ),
    ]
    
    # Associative to inhibitory
    assoc_to_inh_rules = [
        ConnectivityRule(
            name="assoc_to_inh",
            source="associative",
            target="inhibitory",
            pattern=ConnectivityPattern.SPARSE_RANDOM,
            probability=0.05,
            synapse_type="assoc_to_inh",
            weight_mean=0.8,
            weight_std=0.1,
            delay_mean=1.0,
            delay_std=0.2,
            allow_autapse=False,
            description="Associative to inhibitory (plastic)"
        ),
    ]
    
    # Inhibitory to associative
    inh_to_assoc_rules = [
        ConnectivityRule(
            name="inh_to_assoc",
            source="inhibitory",
            target="associative",
            pattern=ConnectivityPattern.SPARSE_RANDOM,
            probability=0.05,
            synapse_type="inh_to_assoc",
            weight_mean=-1.5,
            weight_std=0.2,
            delay_mean=0.5,
            delay_std=0.1,
            allow_autapse=False,
            description="Inhibitory to associative (stabilizing)"
        ),
    ]
    
    # Inhibitory to inhibitory
    inh_rules = [
        ConnectivityRule(
            name="inh_to_inh",
            source="inhibitory",
            target="inhibitory",
            pattern=ConnectivityPattern.SPARSE_RANDOM,
            probability=0.02,
            synapse_type="inh_to_inh",
            weight_mean=-1.0,
            weight_std=0.1,
            delay_mean=0.5,
            delay_std=0.1,
            allow_autapse=False,
            description="Inhibitory to inhibitory"
        ),
    ]
    
    connectivity_rules = (
        sensory_to_assoc_rules + 
        assoc_rules + 
        assoc_to_inh_rules + 
        inh_to_assoc_rules + 
        inh_rules
    )
    
    # =========================================================================
    # PLASTICITY RULES
    # =========================================================================
    
    plasticity_rules = [
        PlasticityRule(
            name="stdp_assoc_assoc",
            rule_type=PlasticityRuleType.STDP,
            applies_to=["assoc_to_assoc"],
            tau_plus=20.0,
            tau_minus=20.0,
            a_plus=0.1,
            a_minus=0.1,
            w_min=0.0,
            w_max=2.0,
            pre_synaptic=True,
            post_synaptic=True,
            description="STDP for associative-associative synapses"
        ),
        PlasticityRule(
            name="stdp_assoc_inh",
            rule_type=PlasticityRuleType.STDP,
            applies_to=["assoc_to_inh"],
            tau_plus=20.0,
            tau_minus=20.0,
            a_plus=0.05,
            a_minus=0.05,
            w_min=0.0,
            w_max=1.0,
            pre_synaptic=True,
            post_synaptic=True,
            description="STDP for associative-inhibitory synapses"
        ),
    ]
    
    # =========================================================================
    # HOMEOSTATIC RULES
    # =========================================================================

    homeostatic_rules = [
        HomeostaticRule(
            name="weight_norm_recurrent",
            mechanism=HomeostaticMechanism.WEIGHT_NORMALIZATION,
            applies_to=["assoc_to_assoc", "assoc_to_inh"],
            apply_interval=200.0,
            description=(
                "Hold each neuron's incoming recurrent (assoc->assoc) and "
                "recurrent-drive (assoc->inh) weight sum at its initial value, "
                "so pair-based STDP reshapes the weight distribution without "
                "collapsing the network to zero. See "
                "[[Neuromorphic_Homeostasis_Implementation]]."
            ),
        ),
    ]

    # =========================================================================
    # OBSERVABLES
    # =========================================================================
    
    # Sensory observables (per feature)
    sensory_observables = [
        ObservableSpec(
            name=f"sensory_f{i}_rate",
            observable_type="firing_rate",
            source_population=f"sensory_f{i}",
            aggregation="mean",
            window_size=50.0,
            sample_rate=20.0,
            description=f"Firing rate of sensory feature {i}"
        )
        for i in range(n_features)
    ]
    
    # Associative observables
    assoc_observables = [
        ObservableSpec(
            name="assoc_firing_rate",
            observable_type="firing_rate",
            source_population="associative",
            aggregation="mean",
            window_size=50.0,
            sample_rate=20.0,
            description="Mean firing rate of associative population"
        ),
        ObservableSpec(
            name="assoc_weight_mean",
            observable_type="plasticity_statistics",
            source_connection="assoc_to_assoc",
            aggregation="mean",
            window_size=500.0,
            sample_rate=2.0,
            description="Mean weight of associative-associative synapses"
        ),
        ObservableSpec(
            name="assoc_weight_std",
            observable_type="plasticity_statistics",
            source_connection="assoc_to_assoc",
            aggregation="std",
            window_size=500.0,
            sample_rate=2.0,
            description="Std of associative-associative weights"
        ),
        ObservableSpec(
            name="assoc_synchrony",
            observable_type="synchrony",
            source_population="associative",
            aggregation="mean",
            window_size=100.0,
            sample_rate=10.0,
            description="Synchrony measure of associative population"
        ),
    ]
    
    # Inhibitory observables
    inh_observables = [
        ObservableSpec(
            name="inh_firing_rate",
            observable_type="firing_rate",
            source_population="inhibitory",
            aggregation="mean",
            window_size=50.0,
            sample_rate=20.0,
            description="Mean firing rate of inhibitory population"
        ),
    ]
    
    # Network-level observables
    network_observables = [
        ObservableSpec(
            name="total_spikes",
            observable_type="firing_rate",
            aggregation="sum",
            window_size=100.0,
            sample_rate=10.0,
            description="Total spike count across all populations"
        ),
        ObservableSpec(
            name="network_topology",
            observable_type="topology",
            aggregation="raw",
            window_size=10000.0,
            sample_rate=0.1,
            description="Full network connectivity snapshot"
        ),
    ]
    
    observables = (
        sensory_observables + 
        assoc_observables + 
        inh_observables + 
        network_observables
    )
    
    # =========================================================================
    # NEUROMODULATORS
    # =========================================================================
    
    # Dopamine gates the recurrent (three-factor) STDP. It is released on a
    # correct trial and decays back to baseline, so the network reinforces the
    # recurrent traces that produce correct behavior instead of letting
    # unsupervised STDP erode them.
    neuromodulators = [
        NeuromodulatorSpec(
            name="dopamine",
            neuromodulator_type=NeuromodulatorType.DOPAMINE,
            baseline=0.0,
            release_amount=1.0,
            tau_decay=100.0,
            trigger_on_reward=True,
            description="Reward signal gating recurrent plasticity",
        ),
    ]
    
    # =========================================================================
    # CREATE GENOME
    # =========================================================================
    
    genome = DevelopmentalGenome(
        version="1.0",
        name=name,
        description=f"DMS task genome: {n_features}×{n_neurons_per_feature} sensory, {n_associative} associative, {n_inhibitory} inhibitory",
        neuron_types=neuron_types,
        synapse_types=synapse_types,
        populations=populations,
        connectivity_rules=connectivity_rules,
        plasticity_rules=plasticity_rules,
        homeostatic_rules=homeostatic_rules,
        neuromodulators=neuromodulators,
        observables=observables,
    )
    
    return genome


def create_minimal_dms_genome() -> DevelopmentalGenome:
    """
    Create a minimal DMS genome for quick testing.
    
    Uses smaller numbers for faster simulation:
    - 2 features × 50 neurons = 100 sensory neurons
    - 400 associative neurons
    - 100 inhibitory neurons
    - Total: 600 neurons
    """
    return create_dms_genome(
        name="dms_minimal",
        n_features=2,
        n_neurons_per_feature=50,
        n_associative=400,
        n_inhibitory=100,
    )


if __name__ == "__main__":
    print("Creating full DMS genome...")
    genome = create_dms_genome(
        name="dms_v1_full",
        n_features=10,
        n_neurons_per_feature=100,
        n_associative=8000,
        n_inhibitory=2000,
    )
    
    print(f"Genome: {genome.name}")
    print(f"Description: {genome.description}")
    print()
    
    print("Components:")
    print(f"  Neuron types: {len(genome.neuron_types)}")
    for nt in genome.neuron_types:
        print(f"    - {nt.name} ({nt.model.value})")
    print()
    
    print(f"  Synapse types: {len(genome.synapse_types)}")
    for st in genome.synapse_types:
        print(f"    - {st.name} ({st.synapse_type.value})")
    print()
    
    print(f"  Populations: {len(genome.populations)}")
    total_neurons = sum(p.size for p in genome.populations)
    print(f"    Total neurons: {total_neurons}")
    for pop in genome.populations:
        print(f"    - {pop.name}: {pop.size} neurons ({pop.role})")
    print()
    
    print(f"  Connectivity rules: {len(genome.connectivity_rules)}")
    for cr in genome.connectivity_rules:
        print(f"    - {cr.name}: {cr.source} -> {cr.target} ({cr.pattern.value})")
    print()
    
    print(f"  Plasticity rules: {len(genome.plasticity_rules)}")
    for pr in genome.plasticity_rules:
        print(f"    - {pr.name} ({pr.rule_type.value}) -> {pr.applies_to}")
    print()
    
    print(f"  Observables: {len(genome.observables)}")
    print()
    
    # Validate
    print("Validating genome...")
    try:
        json_data = genome.to_dict()
        loaded = DevelopmentalGenome.from_dict(json_data)
        print("  ✓ Serialization/deserialization successful")
    except Exception as e:
        print(f"  ✗ Error: {e}")
        raise
    
    # Save
    genome.save("dms_genome_v1.json")
    print(f"  ✓ Saved to dms_genome_v1.json")
    
    # Test compilation
    print()
    print("Testing compilation...")
    from genome_compiler import GenomeCompiler
    
    compiler = GenomeCompiler(seed=42)
    
    # Use minimal genome for faster testing
    print("Creating minimal DMS genome...")
    minimal_genome = create_minimal_dms_genome()
    
    print(f"Minimal genome: {minimal_genome.name}")
    total_minimal = sum(p.size for p in minimal_genome.populations)
    print(f"Total neurons: {total_minimal}")
    
    print("Compiling minimal genome...")
    network = compiler.compile(minimal_genome)
    
    print("Running for 100ms...")
    network.run(duration=100.0, report='text')
    
    print()
    print("Results:")
    for pop_name in network.population_sizes:
        spikes = network.get_spike_count(pop_name)
        rate = network.get_firing_rate(pop_name)
        print(f"  {pop_name}: {spikes} spikes, {rate:.2f} Hz")
    
    print()
    print("DMS genome creation complete!")
