"""
Neuromorphic Co-Development Framework - Stimulus Encoder

Maps a binary stimulus vector (one bit per feature) to Poisson spike trains
that drive the sensory layer. This is checklist step 2 of the seed task spec:

    "map 10-bit vectors to Poisson spike trains in the sensory layer
     (50 Hz ON / 0 Hz OFF)."

The encoder is decoupled from the genome: it takes the compiled sensory
``NeuronGroup`` objects (one per feature) and produces independent Poisson
input for each, so the same encoder can drive any genome that exposes a
feature-by-feature sensory layout.

Author: Generated by Mistral Vibe
Date: 2026-09-02
"""

from __future__ import annotations

from typing import List, Optional, Sequence, Tuple

import numpy as np
import brian2 as b2


class StimulusEncoder:
    """
    Converts binary feature vectors into Poisson spike input.

    Each bit corresponds to one sensory sub-population. A set bit (1) drives
    its sub-population with an independent Poisson train at ``rate_on``; a
    clear bit (0) drives it at 0 Hz (no spikes).

    Parameters
    ----------
    n_features:
        Number of stimulus features (bits). Matches the sensory population
        count of the genome being driven.
    n_neurons_per_feature:
        Number of sensory neurons per feature sub-population.
    rate_on:
        Poisson firing rate (Hz) for an ON feature.
    input_weight:
        EPSP amplitude (mV) applied to a sensory neuron on each input spike.
        Must be large enough for a sensory neuron to reach threshold.
    seed:
        Seed for reproducible spike generation (passed to Brian2's runtime).
    """

    def __init__(
        self,
        n_features: int = 10,
        n_neurons_per_feature: int = 100,
        rate_on: float = 50.0,
        input_weight: float = 20.0,
        seed: Optional[int] = None,
    ):
        self.n_features = int(n_features)
        self.n_neurons_per_feature = int(n_neurons_per_feature)
        self.rate_on = float(rate_on)
        self.input_weight = float(input_weight)
        self.seed = seed

    def validate(self, stimulus: Sequence[int]) -> np.ndarray:
        """Validate and normalize a stimulus vector to a 0/1 int array."""
        s = np.asarray(stimulus, dtype=int)
        if s.ndim != 1 or len(s) != self.n_features:
            raise ValueError(
                f"Stimulus must be a length-{self.n_features} vector, "
                f"got shape {s.shape}"
            )
        if not np.all((s == 0) | (s == 1)):
            raise ValueError("Stimulus must be binary (0/1) values only")
        return s

    def create_input(
        self,
        stimulus: Sequence[int],
        sensory_groups: Sequence[b2.NeuronGroup],
        on_pre: str = "v_post += w * mV",
    ) -> List[Tuple[b2.PoissonGroup, b2.Synapses]]:
        """
        Build Poisson input for each feature sub-population.

        Parameters
        ----------
        stimulus:
            Binary vector of length ``n_features``.
        sensory_groups:
            One ``NeuronGroup`` per feature, in feature order.
        on_pre:
            Synaptic effect on the sensory neuron per input spike.

        Returns
        -------
        List of ``(PoissonGroup, Synapses)`` tuples, one per feature. The
        caller adds these to the compiled network before running. OFF features
        still get a PoissonGroup (rate 0) so the returned list has a stable,
        predictable shape for the trial runner.
        """
        stimulus = self.validate(stimulus)

        if len(sensory_groups) != self.n_features:
            raise ValueError(
                f"Expected {self.n_features} sensory groups, "
                f"got {len(sensory_groups)}"
            )

        if self.seed is not None:
            b2.seed(self.seed)

        inputs: List[Tuple[b2.PoissonGroup, b2.Synapses]] = []
        for f in range(self.n_features):
            rate = self.rate_on if stimulus[f] else 0.0
            source = b2.PoissonGroup(
                self.n_neurons_per_feature,
                rates=rate * b2.Hz,
                name=f"stimulus_f{f}",
            )
            syn = b2.Synapses(
                source,
                sensory_groups[f],
                "w : 1",
                on_pre=on_pre,
                delay=0.5 * b2.ms,
                name=f"stimulus_syn_f{f}",
            )
            syn.connect(j="i")  # one-to-one: source i -> sensory neuron i
            syn.w = self.input_weight
            inputs.append((source, syn))

        return inputs


if __name__ == "__main__":
    # Smoke test: drive a small DMS genome with a stimulus and confirm that
    # ON features fire while OFF features stay silent, and that the driven
    # associative layer exhibits STDP weight drift.
    from genome_compiler import GenomeCompiler
    from sample_genome_dms import create_dms_genome

    b2.start_scope()

    genome = create_dms_genome(
        name="stimulus_demo",
        n_features=2,
        n_neurons_per_feature=50,
        n_associative=200,
        n_inhibitory=50,
    )
    compiler = GenomeCompiler(seed=7)
    net = compiler.compile(genome)

    sensory_groups = [
        net.neuron_groups[f"sensory_f{i}"] for i in range(2)
    ]

    w0 = net.get_mean_weight("assoc_to_assoc")

    encoder = StimulusEncoder(
        n_features=2,
        n_neurons_per_feature=50,
        rate_on=50.0,
        input_weight=20.0,
        seed=7,
    )
    inputs = encoder.create_input([1, 0], sensory_groups)
    for source, syn in inputs:
        net.net.add(source, syn)

    net.run(duration=500.0, report="text")

    for i in range(2):
        rate = net.get_firing_rate(f"sensory_f{i}")
        print(f"feature {i} rate: {rate:.2f} Hz")

    assoc_rate = net.get_firing_rate("associative")
    w1 = net.get_mean_weight("assoc_to_assoc")
    print(f"associative rate: {assoc_rate:.2f} Hz")
    print(f"assoc_to_assoc mean weight: {w0:.4f} -> {w1:.4f} (delta {w1 - w0:+.4f})")
