"""
Neuromorphic Co-Development Framework - Trial Runner

Orchestrates one delayed match-to-sample (DMS) trial against a compiled genome:

    sample -> delay1 -> distractor -> delay2 -> test

and delivers a binary reward. This is checklist step 3 of the seed task spec:

    "orchestrate sample -> delay -> distractor -> delay -> test phases
     and deliver reward."

Design notes
------------
* The genome is compiled once into a persistent ``CompiledNetwork``; its state
  (membrane potentials, synaptic weights, monitors) is never reset between
  trials, so STDP and attractor formation carry over.
* Each trial drives the sensory layer with one ``SpikeGeneratorGroup`` per
  feature whose Poisson spike times are precomputed with numpy (deterministic
  under a numpy RNG). The groups are added to the network for the duration of
  the trial, then removed, so no dead objects accumulate.
* Phase timing is fixed (see ``DEFAULT_DURATIONS``); the runner tracks absolute
  simulation time so it can slice the persistent spike monitor by trial.
* The readout is a template-match: it correlates the associative population's
  per-neuron firing-rate pattern during the *sample* phase with the pattern
  during the *test* phase. A match trial (test == sample) should reproduce the
  sample representation, a non-match trial should not. This requires no trained
  classifier, keeping the trial runner self-contained; the evaluation harness
  can later swap in a learned linear readout.

Author: Generated by Mistral Vibe
Date: 2026-09-02
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, List, Optional, Tuple

import numpy as np
import brian2 as b2

from genome_compiler import CompiledNetwork


# Phase durations in ms, ordered as they appear in a trial.
DEFAULT_DURATIONS: Dict[str, float] = {
    "sample": 100.0,
    "delay1": 200.0,
    "distractor": 100.0,
    "delay2": 200.0,
    "test": 100.0,
}

# Cumulative start offset (ms) of each phase within a trial.
def _phase_offsets(durations: Dict[str, float]) -> Dict[str, float]:
    offsets: Dict[str, float] = {}
    t = 0.0
    for phase, dur in durations.items():
        offsets[phase] = t
        t += dur
    return offsets


@dataclass
class TrialStimuli:
    """The three stimuli and ground-truth match label for one trial."""

    sample: np.ndarray
    distractor: np.ndarray
    test: np.ndarray
    test_is_match: bool


@dataclass
class PhaseStats:
    """Coarse observable for one phase of one trial."""

    spike_count: int
    firing_rate: float  # Hz, averaged over the population


@dataclass
class TrialResult:
    """Everything the evaluation harness needs from a single trial."""

    decision: bool  # True == predicted match
    correct: bool
    reward: float  # +1.0 correct, -1.0 incorrect
    similarity: float  # readout score (correlation)
    test_is_match: bool
    phase_stats: Dict[str, PhaseStats]
    sensory_sample_rates: np.ndarray  # per-feature sensory rate during sample
    sensory_test_rates: np.ndarray  # per-feature sensory rate during test
    sample_pattern: np.ndarray  # associative per-neuron rate during sample
    test_pattern: np.ndarray  # associative per-neuron rate during test
    delay1_pattern: np.ndarray  # associative per-neuron rate during delay1
    delay2_pattern: np.ndarray  # associative per-neuron rate during delay2
    distractor_pattern: np.ndarray  # associative per-neuron rate during distractor


class TrialRunner:
    """Runs DMS trials against a persistent compiled network."""

    def __init__(
        self,
        network: CompiledNetwork,
        n_features: int,
        n_neurons_per_feature: int,
        rate_on: float = 50.0,
        input_weight: float = 20.0,
        durations: Optional[Dict[str, float]] = None,
        readout_threshold: float = 0.3,
        associative_population: str = "associative",
        seed: Optional[int] = None,
        report: Optional[str] = "text",
    ):
        """
        Parameters
        ----------
        network:
            Compiled network (with ``associative`` and ``sensory_f*`` groups).
        n_features:
            Number of stimulus bits; must match the genome's sensory layout.
        n_neurons_per_feature:
            Sensory neurons per feature (matches ``sensory_f*`` group size).
        rate_on:
            Poisson rate (Hz) for an ON feature.
        input_weight:
            EPSP amplitude (mV) per input spike on a sensory neuron.
        durations:
            Phase name -> duration (ms) map, in trial order.
        readout_threshold:
            Correlation above which the runner predicts "match".
        associative_population:
            Name of the population the readout observes.
        seed:
            Seed for stimulus spike generation.
        report:
            Brian2 run report mode ('text', 'stdout', or None to silence).
        """
        self.network = network
        self.n_features = int(n_features)
        self.n_neurons_per_feature = int(n_neurons_per_feature)
        self.rate_on = float(rate_on)
        self.input_weight = float(input_weight)
        self.durations = durations or dict(DEFAULT_DURATIONS)
        self.offsets = _phase_offsets(self.durations)
        self.trial_duration = sum(self.durations.values())
        self.readout_threshold = float(readout_threshold)
        self.associative_population = associative_population
        self.report = report
        self.rng = np.random.default_rng(seed)

        # Absolute simulation time already elapsed (ms). The network has been
        # running for ``network.run_time`` ms at construction; track from there.
        self.elapsed_ms = float(network.run_time)

        self.sensory_names = [f"sensory_f{i}" for i in range(self.n_features)]
        self._validate()

    def _validate(self) -> None:
        missing = [n for n in self.sensory_names if n not in self.network.neuron_groups]
        if missing:
            raise ValueError(f"Sensory populations not found: {missing}")
        if self.associative_population not in self.network.neuron_groups:
            raise ValueError(
                f"Associative population '{self.associative_population}' not found"
            )
        if self.associative_population not in self.network.spike_monitors:
            raise ValueError(
                f"No spike monitor for '{self.associative_population}'"
            )

    # ------------------------------------------------------------------
    # Stimulus generation
    # ------------------------------------------------------------------
    def generate_stimuli(self) -> TrialStimuli:
        """Draw a random trial: random sample, distractor (H>=1), 50/50 match."""
        sample = self.rng.integers(0, 2, size=self.n_features)
        distractor = sample.copy()
        # flip at least one bit so distractor != sample
        flip = self.rng.integers(0, self.n_features)
        distractor[flip] = 1 - distractor[flip]

        test_is_match = bool(self.rng.integers(0, 2))
        if test_is_match:
            test = sample.copy()
        else:
            test = sample.copy()
            flip = self.rng.integers(0, self.n_features)
            test[flip] = 1 - test[flip]

        return TrialStimuli(
            sample=sample,
            distractor=distractor,
            test=test,
            test_is_match=test_is_match,
        )

    # ------------------------------------------------------------------
    # Poisson spike generation
    # ------------------------------------------------------------------
    def _poisson_spikes(
        self, rate: float, t0_ms: float, duration_ms: float
    ) -> Tuple[np.ndarray, np.ndarray]:
        """
        Return (neuron_indices, times_ms) for one feature over a window.

        Spikes are generated as an independent Bernoulli process on a time grid
        of width ``dt`` (the network clock step), so each neuron emits at most
        one spike per time step — a requirement of ``SpikeGeneratorGroup``.
        """
        n = self.n_neurons_per_feature
        dt_ms = float(b2.defaultclock.dt / b2.ms)
        n_bins = int(np.round(duration_ms / dt_ms))
        p = rate * (dt_ms / 1000.0)
        if n_bins == 0 or p <= 0.0:
            return np.zeros(0, dtype=int), np.zeros(0, dtype=float)

        spikes = self.rng.random((n, n_bins)) < p
        neuron_idx, bin_idx = np.nonzero(spikes)
        if neuron_idx.size == 0:
            return np.zeros(0, dtype=int), np.zeros(0, dtype=float)

        order = np.argsort(bin_idx, kind="stable")
        neuron_idx = neuron_idx[order]
        bin_idx = bin_idx[order]
        times_ms = t0_ms + bin_idx * dt_ms
        return neuron_idx, times_ms

    def _build_input_groups(
        self, stimuli: TrialStimuli
    ) -> List[Tuple[b2.SpikeGeneratorGroup, b2.Synapses]]:
        """
        Build one SpikeGeneratorGroup + Synapses per feature that is ON in any
        phase, with absolute spike times across the whole trial.
        """
        # Which stimulus (if any) drives each phase, in trial order.
        phase_stimulus = {
            "sample": stimuli.sample,
            "delay1": None,
            "distractor": stimuli.distractor,
            "delay2": None,
            "test": stimuli.test,
        }

        # Accumulate (indices, times) per feature.
        feat_idx: List[List[int]] = [[] for _ in range(self.n_features)]
        feat_times: List[List[float]] = [[] for _ in range(self.n_features)]
        for phase in self.durations:
            stim = phase_stimulus[phase]
            if stim is None:
                continue
            t0 = self.elapsed_ms + self.offsets[phase]
            dur = self.durations[phase]
            for f in range(self.n_features):
                if not stim[f]:
                    continue
                idx, times = self._poisson_spikes(self.rate_on, t0, dur)
                feat_idx[f].extend(idx.tolist())
                feat_times[f].extend(times.tolist())

        groups: List[Tuple[b2.SpikeGeneratorGroup, b2.Synapses]] = []
        for f in range(self.n_features):
            if not feat_times[f]:
                continue
            idx = np.asarray(feat_idx[f], dtype=int)
            times_ms = np.asarray(feat_times[f], dtype=float)
            source = b2.SpikeGeneratorGroup(
                self.n_neurons_per_feature,
                indices=idx,
                times=(times_ms / 1000.0) * b2.second,
                name=f"trial_input_f{f}",
            )
            target = self.network.neuron_groups[self.sensory_names[f]]
            syn = b2.Synapses(
                source,
                target,
                "w : 1",
                on_pre="v_post += w * mV",
                delay=0.5 * b2.ms,
                name=f"trial_input_syn_f{f}",
            )
            syn.connect(j="i")
            syn.w = self.input_weight
            groups.append((source, syn))

        return groups

    # ------------------------------------------------------------------
    # Observables / readout
    # ------------------------------------------------------------------
    def _population_pattern(
        self, population: str, t0_ms: float, duration_ms: float
    ) -> np.ndarray:
        """Per-neuron firing rate (Hz) over a time window."""
        mon = self.network.spike_monitors[population]
        times = np.asarray(mon.t / b2.ms)
        indices = np.asarray(mon.i)
        mask = (times >= t0_ms) & (times < t0_ms + duration_ms)
        size = self.network.population_sizes[population]
        counts = np.bincount(indices[mask], minlength=size)
        return counts / (duration_ms / 1000.0)

    def _phase_stats(self, population: str, t0_ms: float, duration_ms: float) -> PhaseStats:
        pattern = self._population_pattern(population, t0_ms, duration_ms)
        return PhaseStats(
            spike_count=int(pattern.sum() * (duration_ms / 1000.0)),
            firing_rate=float(np.mean(pattern)),
        )

    @staticmethod
    def _pearson(a: np.ndarray, b: np.ndarray) -> float:
        a = a.astype(float)
        b = b.astype(float)
        if a.std() == 0.0 or b.std() == 0.0:
            return 0.0
        return float(np.corrcoef(a, b)[0, 1])

    def _sensory_rates(self, phase: str) -> np.ndarray:
        """Per-feature mean sensory firing rate during a phase."""
        t0 = self.elapsed_ms + self.offsets[phase]
        dur = self.durations[phase]
        rates = np.zeros(self.n_features)
        for f, name in enumerate(self.sensory_names):
            mon = self.network.spike_monitors[name]
            times = np.asarray(mon.t / b2.ms)
            mask = (times >= t0) & (times < t0 + dur)
            rates[f] = mask.sum() / (self.n_neurons_per_feature * (dur / 1000.0))
        return rates

    # ------------------------------------------------------------------
    # Trial execution
    # ------------------------------------------------------------------
    def run_trial(self, stimuli: TrialStimuli) -> TrialResult:
        """
        Run one full trial and return the decision, reward, and observables.
        """
        # Reset transient activity (membrane potential, slow NMDA current,
        # adaptation) so the trial starts from a clean baseline; the synaptic
        # weights shaped by STDP persist across trials.
        self.network.reset_transient_state()

        # Build input for this trial (absolute times from self.elapsed_ms).
        input_groups = self._build_input_groups(stimuli)
        for source, syn in input_groups:
            self.network.net.add(source, syn)

        t_start = self.elapsed_ms
        self.network.run(self.trial_duration, report=self.report)

        # Remove trial input so it does not accumulate across trials.
        for source, syn in input_groups:
            self.network.net.remove(source, syn)

        # --- readout -------------------------------------------------------
        sample_pattern = self._population_pattern(
            self.associative_population,
            t_start + self.offsets["sample"],
            self.durations["sample"],
        )
        test_pattern = self._population_pattern(
            self.associative_population,
            t_start + self.offsets["test"],
            self.durations["test"],
        )
        delay1_pattern = self._population_pattern(
            self.associative_population,
            t_start + self.offsets["delay1"],
            self.durations["delay1"],
        )
        delay2_pattern = self._population_pattern(
            self.associative_population,
            t_start + self.offsets["delay2"],
            self.durations["delay2"],
        )
        distractor_pattern = self._population_pattern(
            self.associative_population,
            t_start + self.offsets["distractor"],
            self.durations["distractor"],
        )
        similarity = self._pearson(sample_pattern, test_pattern)
        decision = similarity >= self.readout_threshold
        correct = decision == stimuli.test_is_match
        reward = 1.0 if correct else -1.0

        # Deliver the reward to the neuromodulator system: releases dopamine on
        # a correct trial and suppresses it on an error, gating the THREE_FACTOR
        # synapses' plasticity for the next trial.
        self.network.apply_reward(reward, self.trial_duration)

        # --- phase stats ---------------------------------------------------
        phase_stats: Dict[str, PhaseStats] = {}
        for phase, dur in self.durations.items():
            phase_stats[phase] = self._phase_stats(
                self.associative_population,
                t_start + self.offsets[phase],
                dur,
            )

        result = TrialResult(
            decision=decision,
            correct=correct,
            reward=reward,
            similarity=similarity,
            test_is_match=stimuli.test_is_match,
            phase_stats=phase_stats,
            sensory_sample_rates=self._sensory_rates("sample"),
            sensory_test_rates=self._sensory_rates("test"),
            sample_pattern=sample_pattern,
            test_pattern=test_pattern,
            delay1_pattern=delay1_pattern,
            delay2_pattern=delay2_pattern,
            distractor_pattern=distractor_pattern,
        )

        self.elapsed_ms += self.trial_duration
        return result


if __name__ == "__main__":
    # Smoke test: run a match and a non-match trial on a small DMS genome and
    # confirm the phases fire in the right windows and the readout returns a
    # score.
    from genome_compiler import GenomeCompiler
    from sample_genome_dms import create_dms_genome

    b2.start_scope()

    genome = create_dms_genome(
        name="trial_demo",
        n_features=2,
        n_neurons_per_feature=20,
        n_associative=150,
        n_inhibitory=40,
    )
    compiler = GenomeCompiler(seed=3)
    net = compiler.compile(genome)

    runner = TrialRunner(
        network=net,
        n_features=2,
        n_neurons_per_feature=20,
        rate_on=50.0,
        input_weight=20.0,
        readout_threshold=0.3,
        seed=3,
    )

    for label, is_match in (("MATCH", True), ("NON-MATCH", False)):
        stimuli = runner.generate_stimuli()
        # force the ground-truth label for the demo
        stimuli.test_is_match = is_match
        stimuli.test = stimuli.sample.copy() if is_match else 1 - stimuli.sample
        result = runner.run_trial(stimuli)
        assoc_rates = {
            p: f"{s.firing_rate:.2f}" for p, s in result.phase_stats.items()
        }
        print(f"\n{label} trial: sample={stimuli.sample}, test={stimuli.test}")
        print(f"  decision={'match' if result.decision else 'non-match'} "
              f"correct={result.correct} reward={result.reward:+.0f} "
              f"similarity={result.similarity:.3f}")
        print(f"  assoc rates (Hz) by phase: {assoc_rates}")
        print(f"  sensory sample rates: {np.round(result.sensory_sample_rates, 1)}")
        print(f"  sensory test rates:   {np.round(result.sensory_test_rates, 1)}")
